# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# python-doc bot, 2025
# André Moreira <afrmscb@gmail.com>, 2025
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.13\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-15 15:08+0000\n"
"PO-Revision-Date: 2025-09-15 01:05+0000\n"
"Last-Translator: André Moreira <afrmscb@gmail.com>, 2025\n"
"Language-Team: Portuguese (Portugal) (https://app.transifex.com/python-doc/"
"teams/5390/pt_PT/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_PT\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: ../../tutorial/errors.rst:5
msgid "Errors and Exceptions"
msgstr "Erros e exceções"

#: ../../tutorial/errors.rst:7
msgid ""
"Until now error messages haven't been more than mentioned, but if you have "
"tried out the examples you have probably seen some.  There are (at least) "
"two distinguishable kinds of errors: *syntax errors* and *exceptions*."
msgstr ""
"Até agora, as mensagens de erro não foram mais do que mencionadas, mas se "
"experimentou os exemplos, provavelmente já viu algumas. Existem (pelo menos) "
"dois tipos distintos de erros: *erros de sintaxe* e *exceções*."

#: ../../tutorial/errors.rst:15
msgid "Syntax Errors"
msgstr "Erros de sintaxe"

#: ../../tutorial/errors.rst:17
msgid ""
"Syntax errors, also known as parsing errors, are perhaps the most common "
"kind of complaint you get while you are still learning Python::"
msgstr ""
"Os erros de sintaxe, também conhecidos como erros de análise, são "
"provavelmente o tipo de mensagem de erro mais comum que recebe enquanto "
"ainda está a aprender Python:"

#: ../../tutorial/errors.rst:20
msgid ""
">>> while True print('Hello world')\n"
"  File \"<stdin>\", line 1\n"
"    while True print('Hello world')\n"
"               ^^^^^\n"
"SyntaxError: invalid syntax"
msgstr ""
">>> while True print('Olá mundo')\n"
"  File \"<stdin>\", line 1\n"
"    while True print('Olá mundo')\n"
"               ^^^^^\n"
"SyntaxError: sintaxe inválida"

#: ../../tutorial/errors.rst:26
msgid ""
"The parser repeats the offending line and displays little arrows pointing at "
"the place where the error was detected.  Note that this is not always the "
"place that needs to be fixed.  In the example, the error is detected at the "
"function :func:`print`, since a colon (``':'``) is missing just before it."
msgstr ""
"O analisador repete a linha problemática e mostra pequenas setas a apontar "
"para o local onde o erro foi detetado. Note que este não é sempre o local "
"que precisa de ser corrigido. No exemplo, o erro é detetado na função :func:"
"`print`, uma vez que falta um dois-pontos (``:``) logo antes dela."

#: ../../tutorial/errors.rst:31
msgid ""
"The file name (``<stdin>`` in our example) and line number are printed so "
"you know where to look in case the input came from a file."
msgstr ""
"O nome do ficheiro (``<stdin>`` no nosso exemplo) e o número da linha são "
"impressos para que saiba onde procurar caso a entrada venha de um ficheiro."

#: ../../tutorial/errors.rst:38
msgid "Exceptions"
msgstr "Exceções"

#: ../../tutorial/errors.rst:40
msgid ""
"Even if a statement or expression is syntactically correct, it may cause an "
"error when an attempt is made to execute it. Errors detected during "
"execution are called *exceptions* and are not unconditionally fatal: you "
"will soon learn how to handle them in Python programs.  Most exceptions are "
"not handled by programs, however, and result in error messages as shown "
"here::"
msgstr ""
"Mesmo que uma instrução ou expressão esteja sintaticamente correta, pode "
"causar um erro quando se tenta executá-la. Os erros detetados durante a "
"execução são chamados *exceções* e não são necessariamente fatais: em breve "
"aprenderá a tratá-los em programas Python. No entanto, a maioria das "
"exceções não são tratadas pelos programas e resultam em mensagens de erro "
"como mostrado aqui:"

#: ../../tutorial/errors.rst:46
msgid ""
">>> 10 * (1/0)\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    10 * (1/0)\n"
"          ~^~\n"
"ZeroDivisionError: division by zero\n"
">>> 4 + spam*3\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    4 + spam*3\n"
"        ^^^^\n"
"NameError: name 'spam' is not defined\n"
">>> '2' + 2\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    '2' + 2\n"
"    ~~~~^~~\n"
"TypeError: can only concatenate str (not \"int\") to str"
msgstr ""
">>> 10 * (1/0)\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    10 * (1/0)\n"
"          ~^~\n"
"ZeroDivisionError: divisão por zero\n"
">>> 4 + spam*3\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    4 + spam*3\n"
"        ^^^^\n"
"NameError: o nome 'spam' não está definido\n"
">>> '2' + 2\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    '2' + 2\n"
"    ~~~~^~~\n"
"TypeError: só é possível concatenar str (não \"int\") com str"

#: ../../tutorial/errors.rst:65
msgid ""
"The last line of the error message indicates what happened. Exceptions come "
"in different types, and the type is printed as part of the message: the "
"types in the example are :exc:`ZeroDivisionError`, :exc:`NameError` and :exc:"
"`TypeError`. The string printed as the exception type is the name of the "
"built-in exception that occurred.  This is true for all built-in exceptions, "
"but need not be true for user-defined exceptions (although it is a useful "
"convention). Standard exception names are built-in identifiers (not reserved "
"keywords)."
msgstr ""
"A última linha da mensagem de erro indica o que aconteceu. As exceções vêm "
"em diferentes tipos, e o tipo é impresso como parte da mensagem: os tipos no "
"exemplo são :exc:`ZeroDivisionError`, :exc:`NameError` e :exc:`TypeError`. A "
"string impressa como o tipo de exceção é o nome da exceção incorporada que "
"ocorreu. Isto é verdade para todas as exceções incorporadas, mas não precisa "
"de ser verdade para exceções definidas pelo utilizador (embora seja uma "
"convenção útil). Os nomes de exceções padrão são identificadores "
"incorporados (não palavras reservadas)."

#: ../../tutorial/errors.rst:73
msgid ""
"The rest of the line provides detail based on the type of exception and what "
"caused it."
msgstr ""
"O resto da linha fornece detalhes com base no tipo de exceção e naquilo que "
"a causou."

#: ../../tutorial/errors.rst:76
msgid ""
"The preceding part of the error message shows the context where the "
"exception occurred, in the form of a stack traceback. In general it contains "
"a stack traceback listing source lines; however, it will not display lines "
"read from standard input."
msgstr ""
"A parte anterior da mensagem de erro mostra o contexto onde a exceção "
"ocorreu, na forma de um rastreio de pilha. Em geral, contém um rastreio de "
"pilha que lista as linhas de origem; no entanto, não mostrará linhas lidas a "
"partir da entrada padrão."

#: ../../tutorial/errors.rst:81
msgid ""
":ref:`bltin-exceptions` lists the built-in exceptions and their meanings."
msgstr ""
":ref:`bltin-exceptions` lista as exceções incorporadas e os seus "
"significados."

#: ../../tutorial/errors.rst:87
msgid "Handling Exceptions"
msgstr "Tratamento de exceções"

#: ../../tutorial/errors.rst:89
msgid ""
"It is possible to write programs that handle selected exceptions. Look at "
"the following example, which asks the user for input until a valid integer "
"has been entered, but allows the user to interrupt the program (using :kbd:"
"`Control-C` or whatever the operating system supports); note that a user-"
"generated interruption is signalled by raising the :exc:`KeyboardInterrupt` "
"exception. ::"
msgstr ""
"É possível escrever programas que tratam exceções selecionadas. Veja o "
"seguinte exemplo, que pede ao utilizador para introduzir dados até que um "
"inteiro válido seja inserido, mas permite ao utilizador interromper o "
"programa (usando :kbd:`Control-C` ou o que o sistema operativo suportar); "
"note que uma interrupção gerada pelo utilizador é sinalizada levantando a "
"exceção :exc:`KeyboardInterrupt`:"

#: ../../tutorial/errors.rst:95
msgid ""
">>> while True:\n"
"...     try:\n"
"...         x = int(input(\"Please enter a number: \"))\n"
"...         break\n"
"...     except ValueError:\n"
"...         print(\"Oops!  That was no valid number.  Try again...\")\n"
"..."
msgstr ""
">>> while True:\n"
"...     try:\n"
"...         x = int(input(\"Por favor, introduza um número: \"))\n"
"...         break\n"
"...     except ValueError:\n"
"...         print(\"Ops! Isso não é um número válido. Tente novamente...\")\n"
"..."

#: ../../tutorial/errors.rst:103
msgid "The :keyword:`try` statement works as follows."
msgstr "A instrução :keyword:`try` funciona da seguinte forma."

#: ../../tutorial/errors.rst:105
msgid ""
"First, the *try clause* (the statement(s) between the :keyword:`try` and :"
"keyword:`except` keywords) is executed."
msgstr ""
"Primeiro, a *cláusula try* (a(s) instrução(ões) entre as palavras-chave :"
"keyword:`try` e :keyword:`except`) é executada."

#: ../../tutorial/errors.rst:108
msgid ""
"If no exception occurs, the *except clause* is skipped and execution of the :"
"keyword:`try` statement is finished."
msgstr ""
"Se não ocorrer nenhuma exceção, a *cláusula except* é ignorada e a execução "
"da instrução :keyword:`try` termina."

#: ../../tutorial/errors.rst:111
msgid ""
"If an exception occurs during execution of the :keyword:`try` clause, the "
"rest of the clause is skipped.  Then, if its type matches the exception "
"named after the :keyword:`except` keyword, the *except clause* is executed, "
"and then execution continues after the try/except block."
msgstr ""
"Se ocorrer uma exceção durante a execução da cláusula :keyword:`try`, o "
"resto da cláusula é ignorado. Em seguida, se o seu tipo corresponder à "
"exceção nomeada após a palavra-chave :keyword:`except`, a *cláusula except* "
"é executada, e depois a execução continua após o bloco try/except."

#: ../../tutorial/errors.rst:116
msgid ""
"If an exception occurs which does not match the exception named in the "
"*except clause*, it is passed on to outer :keyword:`try` statements; if no "
"handler is found, it is an *unhandled exception* and execution stops with an "
"error message."
msgstr ""
"Se ocorrer uma exceção que não corresponde à exceção nomeada na *cláusula "
"except*, ela é passada para instruções :keyword:`try` externas; se nenhum "
"manipulador for encontrado, é uma *exceção não tratada* e a execução para "
"com uma mensagem de erro."

#: ../../tutorial/errors.rst:120
msgid ""
"A :keyword:`try` statement may have more than one *except clause*, to "
"specify handlers for different exceptions.  At most one handler will be "
"executed. Handlers only handle exceptions that occur in the corresponding "
"*try clause*, not in other handlers of the same :keyword:`!try` statement.  "
"An *except clause* may name multiple exceptions as a parenthesized tuple, "
"for example::"
msgstr ""
"Uma instrução :keyword:`try` pode ter mais do que uma *cláusula except*, "
"para especificar manipuladores para diferentes exceções. No máximo, um "
"manipulador será executado. Os manipuladores tratam apenas exceções que "
"ocorrem na *cláusula try* correspondente, não em outros manipuladores da "
"mesma instrução :keyword:`!try`. Uma *cláusula except* pode nomear múltiplas "
"exceções como um tuplo entre parênteses, por exemplo:"

#: ../../tutorial/errors.rst:126
msgid ""
"... except (RuntimeError, TypeError, NameError):\n"
"...     pass"
msgstr ""
"... except (RuntimeError, TypeError, NameError):\n"
"...     pass"

#: ../../tutorial/errors.rst:129
msgid ""
"A class in an :keyword:`except` clause matches exceptions which are "
"instances of the class itself or one of its derived classes (but not the "
"other way around --- an *except clause* listing a derived class does not "
"match instances of its base classes). For example, the following code will "
"print B, C, D in that order::"
msgstr ""
"Uma classe numa cláusula :keyword:`except` corresponde a exceções que são "
"instâncias da própria classe ou de uma das suas classes derivadas (mas não o "
"contrário — uma *cláusula except* que liste uma classe derivada não "
"corresponde a instâncias das suas classes base). Por exemplo, o seguinte "
"código imprimirá B, C, D por essa ordem:"

#: ../../tutorial/errors.rst:134
msgid ""
"class B(Exception):\n"
"    pass\n"
"\n"
"class C(B):\n"
"    pass\n"
"\n"
"class D(C):\n"
"    pass\n"
"\n"
"for cls in [B, C, D]:\n"
"    try:\n"
"        raise cls()\n"
"    except D:\n"
"        print(\"D\")\n"
"    except C:\n"
"        print(\"C\")\n"
"    except B:\n"
"        print(\"B\")"
msgstr ""
"class B(Exception):\n"
"    pass\n"
"\n"
"class C(B):\n"
"    pass\n"
"\n"
"class D(C):\n"
"    pass\n"
"\n"
"for cls in [B, C, D]:\n"
"    try:\n"
"        raise cls()\n"
"    except D:\n"
"        print(\"D\")\n"
"    except C:\n"
"        print(\"C\")\n"
"    except B:\n"
"        print(\"B\")"

#: ../../tutorial/errors.rst:153
msgid ""
"Note that if the *except clauses* were reversed (with ``except B`` first), "
"it would have printed B, B, B --- the first matching *except clause* is "
"triggered."
msgstr ""
"Note que se as *cláusulas except* estivessem invertidas (com ``except B`` "
"primeiro), imprimiria B, B, B — a primeira *cláusula except* correspondente "
"é acionada."

#: ../../tutorial/errors.rst:156
msgid ""
"When an exception occurs, it may have associated values, also known as the "
"exception's *arguments*. The presence and types of the arguments depend on "
"the exception type."
msgstr ""
"Quando uma exceção ocorre, pode ter valores associados, também conhecidos "
"como *argumentos* da exceção. A presença e os tipos dos argumentos dependem "
"do tipo de exceção."

#: ../../tutorial/errors.rst:160
msgid ""
"The *except clause* may specify a variable after the exception name.  The "
"variable is bound to the exception instance which typically has an ``args`` "
"attribute that stores the arguments. For convenience, builtin exception "
"types define :meth:`~object.__str__` to print all the arguments without "
"explicitly accessing ``.args``.  ::"
msgstr ""
"A *cláusula except* pode especificar uma variável após o nome da exceção. A "
"variável é ligada à instância da exceção, que tipicamente tem um atributo "
"``args`` que armazena os argumentos. Por conveniência, os tipos de exceção "
"incorporados definem :meth:`~object.__str__` para imprimir todos os "
"argumentos sem acessar explicitamente ``.args``:"

#: ../../tutorial/errors.rst:166
msgid ""
">>> try:\n"
"...     raise Exception('spam', 'eggs')\n"
"... except Exception as inst:\n"
"...     print(type(inst))    # the exception type\n"
"...     print(inst.args)     # arguments stored in .args\n"
"...     print(inst)          # __str__ allows args to be printed directly,\n"
"...                          # but may be overridden in exception "
"subclasses\n"
"...     x, y = inst.args     # unpack args\n"
"...     print('x =', x)\n"
"...     print('y =', y)\n"
"...\n"
"<class 'Exception'>\n"
"('spam', 'eggs')\n"
"('spam', 'eggs')\n"
"x = spam\n"
"y = eggs"
msgstr ""
">>> try:\n"
"...     raise Exception('spam', 'ovos')\n"
"... except Exception as inst:\n"
"...     print(type(inst))    # o tipo de exceção\n"
"...     print(inst.args)     # argumentos armazenados em .args\n"
"...     print(inst)          # __str__ permite que os argumentos sejam "
"impressos diretamente,\n"
"...                          # mas pode ser substituído em subclasses de "
"exceção\n"
"...     x, y = inst.args     # desempacotar argumentos\n"
"...     print('x =', x)\n"
"...     print('y =', y)\n"
"...\n"
"<class 'Exception'>\n"
"('spam', 'ovos')\n"
"('spam', 'ovos')\n"
"x = spam\n"
"y = ovos"

#: ../../tutorial/errors.rst:183
msgid ""
"The exception's :meth:`~object.__str__` output is printed as the last part "
"('detail') of the message for unhandled exceptions."
msgstr ""
"A saída do método :meth:`~object.__str__` da exceção é impressa como a "
"última parte ('detalhe') da mensagem para exceções não tratadas."

#: ../../tutorial/errors.rst:186
msgid ""
":exc:`BaseException` is the common base class of all exceptions. One of its "
"subclasses, :exc:`Exception`, is the base class of all the non-fatal "
"exceptions. Exceptions which are not subclasses of :exc:`Exception` are not "
"typically handled, because they are used to indicate that the program should "
"terminate. They include :exc:`SystemExit` which is raised by :meth:`sys."
"exit` and :exc:`KeyboardInterrupt` which is raised when a user wishes to "
"interrupt the program."
msgstr ""
":exc:`BaseException` é a classe base comum de todas as exceções. Uma das "
"suas subclasses, :exc:`Exception`, é a classe base de todas as exceções não "
"fatais. As exceções que não são subclasses de :exc:`Exception` não são "
"tipicamente tratadas, porque são usadas para indicar que o programa deve "
"terminar. Estas incluem :exc:`SystemExit`, que é levantada por :meth:`sys."
"exit`, e :exc:`KeyboardInterrupt`, que é levantada quando um utilizador "
"deseja interromper o programa."

#: ../../tutorial/errors.rst:194
msgid ""
":exc:`Exception` can be used as a wildcard that catches (almost) everything. "
"However, it is good practice to be as specific as possible with the types of "
"exceptions that we intend to handle, and to allow any unexpected exceptions "
"to propagate on."
msgstr ""
":exc:`Exception` pode ser usada como um curinga que captura (quase) tudo. No "
"entanto, é uma boa prática ser o mais específico possível com os tipos de "
"exceções que pretendemos tratar e permitir que quaisquer exceções "
"inesperadas se propaguem."

#: ../../tutorial/errors.rst:199
msgid ""
"The most common pattern for handling :exc:`Exception` is to print or log the "
"exception and then re-raise it (allowing a caller to handle the exception as "
"well)::"
msgstr ""
"O padrão mais comum para tratar :exc:`Exception` é imprimir ou registar a "
"exceção e depois relançá-la (permitindo que o chamador também trate a "
"exceção):"

#: ../../tutorial/errors.rst:203
msgid ""
"import sys\n"
"\n"
"try:\n"
"    f = open('myfile.txt')\n"
"    s = f.readline()\n"
"    i = int(s.strip())\n"
"except OSError as err:\n"
"    print(\"OS error:\", err)\n"
"except ValueError:\n"
"    print(\"Could not convert data to an integer.\")\n"
"except Exception as err:\n"
"    print(f\"Unexpected {err=}, {type(err)=}\")\n"
"    raise"
msgstr ""
"import sys\n"
"\n"
"try:\n"
"    f = open('meuficheiro.txt')\n"
"    s = f.readline()\n"
"    i = int(s.strip())\n"
"except OSError as err:\n"
"    print(\"Erro de SO:\", err)\n"
"except ValueError:\n"
"    print(\"Não foi possível converter os dados para um inteiro.\")\n"
"except Exception as err:\n"
"    print(f\"Inesperado {err=}, {type(err)=}\")\n"
"    raise"

#: ../../tutorial/errors.rst:217
msgid ""
"The :keyword:`try` ... :keyword:`except` statement has an optional *else "
"clause*, which, when present, must follow all *except clauses*.  It is "
"useful for code that must be executed if the *try clause* does not raise an "
"exception. For example::"
msgstr ""
"A instrução :keyword:`try` ... :keyword:`except` tem uma *cláusula else* "
"opcional, que, quando presente, deve seguir todas as *cláusulas except*. É "
"útil para código que deve ser executado se a *cláusula try* não levantar uma "
"exceção. Por exemplo:"

#: ../../tutorial/errors.rst:222
msgid ""
"for arg in sys.argv[1:]:\n"
"    try:\n"
"        f = open(arg, 'r')\n"
"    except OSError:\n"
"        print('cannot open', arg)\n"
"    else:\n"
"        print(arg, 'has', len(f.readlines()), 'lines')\n"
"        f.close()"
msgstr ""
"for arg in sys.argv[1:]:\n"
"    try:\n"
"        f = open(arg, 'r')\n"
"    except OSError:\n"
"        print('não é possível abrir', arg)\n"
"    else:\n"
"        print(arg, 'tem', len(f.readlines()), 'linhas')\n"
"        f.close()"

#: ../../tutorial/errors.rst:231
msgid ""
"The use of the :keyword:`!else` clause is better than adding additional code "
"to the :keyword:`try` clause because it avoids accidentally catching an "
"exception that wasn't raised by the code being protected by the :keyword:`!"
"try` ... :keyword:`!except` statement."
msgstr ""
"O uso da cláusula :keyword:`!else` é melhor do que adicionar código "
"adicional à cláusula :keyword:`try`, porque evita capturar acidentalmente "
"uma exceção que não foi levantada pelo código protegido pela instrução :"
"keyword:`!try` ... :keyword:`!except`."

#: ../../tutorial/errors.rst:236
msgid ""
"Exception handlers do not handle only exceptions that occur immediately in "
"the *try clause*, but also those that occur inside functions that are called "
"(even indirectly) in the *try clause*. For example::"
msgstr ""
"Os manipuladores de exceções não tratam apenas exceções que ocorrem "
"imediatamente na *cláusula try*, mas também aquelas que ocorrem dentro de "
"funções que são chamadas (mesmo indiretamente) na *cláusula try*. Por "
"exemplo:"

#: ../../tutorial/errors.rst:240
msgid ""
">>> def this_fails():\n"
"...     x = 1/0\n"
"...\n"
">>> try:\n"
"...     this_fails()\n"
"... except ZeroDivisionError as err:\n"
"...     print('Handling run-time error:', err)\n"
"...\n"
"Handling run-time error: division by zero"
msgstr ""
">>> def this_fails():\n"
"...     x = 1/0\n"
"...\n"
">>> try:\n"
"...     this_fails()\n"
"... except ZeroDivisionError as err:\n"
"...     print('A tratar erro de execução:', err)\n"
"...\n"
"A tratar erro de execução: divisão por zero"

#: ../../tutorial/errors.rst:254
msgid "Raising Exceptions"
msgstr "Lançamento de exceções"

#: ../../tutorial/errors.rst:256
msgid ""
"The :keyword:`raise` statement allows the programmer to force a specified "
"exception to occur. For example::"
msgstr ""
"A instrução :keyword:`raise` permite ao programador forçar a ocorrência de "
"uma exceção especificada. Por exemplo:"

#: ../../tutorial/errors.rst:259
msgid ""
">>> raise NameError('HiThere')\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    raise NameError('HiThere')\n"
"NameError: HiThere"
msgstr ""
">>> raise NameError('Olá')\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    raise NameError('Olá')\n"
"NameError: Olá"

#: ../../tutorial/errors.rst:265
msgid ""
"The sole argument to :keyword:`raise` indicates the exception to be raised. "
"This must be either an exception instance or an exception class (a class "
"that derives from :class:`BaseException`, such as :exc:`Exception` or one of "
"its subclasses).  If an exception class is passed, it will be implicitly "
"instantiated by calling its constructor with no arguments::"
msgstr ""
"O único argumento para :keyword:`raise` indica a exceção a ser lançada. Isto "
"deve ser uma instância de exceção ou uma classe de exceção (uma classe que "
"deriva de :class:`BaseException`, como :exc:`Exception` ou uma das suas "
"subclasses). Se uma classe de exceção for passada, será implicitamente "
"instanciada chamando o seu construtor sem argumentos:"

#: ../../tutorial/errors.rst:271
msgid "raise ValueError  # shorthand for 'raise ValueError()'"
msgstr "raise ValueError  # abreviatura para 'raise ValueError()'"

#: ../../tutorial/errors.rst:273
msgid ""
"If you need to determine whether an exception was raised but don't intend to "
"handle it, a simpler form of the :keyword:`raise` statement allows you to re-"
"raise the exception::"
msgstr ""
"Se precisar de determinar se uma exceção foi lançada, mas não pretender "
"tratá-la, uma forma mais simples da instrução :keyword:`raise` permite-lhe "
"relançar a exceção:"

#: ../../tutorial/errors.rst:277
msgid ""
">>> try:\n"
"...     raise NameError('HiThere')\n"
"... except NameError:\n"
"...     print('An exception flew by!')\n"
"...     raise\n"
"...\n"
"An exception flew by!\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise NameError('HiThere')\n"
"NameError: HiThere"
msgstr ""
">>> try:\n"
"...     raise NameError('Olá')\n"
"... except NameError:\n"
"...     print('Uma exceção passou por aqui!')\n"
"...     raise\n"
"...\n"
"Uma exceção passou por aqui!\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise NameError('Olá')\n"
"NameError: Olá"

#: ../../tutorial/errors.rst:293
msgid "Exception Chaining"
msgstr "Encadeamento de exceções"

#: ../../tutorial/errors.rst:295
msgid ""
"If an unhandled exception occurs inside an :keyword:`except` section, it "
"will have the exception being handled attached to it and included in the "
"error message::"
msgstr ""
"Se uma exceção não tratada ocorrer dentro de uma secção :keyword:`except`, "
"ela terá a exceção que está a ser tratada anexada e incluída na mensagem de "
"erro:"

#: ../../tutorial/errors.rst:299
msgid ""
">>> try:\n"
"...     open(\"database.sqlite\")\n"
"... except OSError:\n"
"...     raise RuntimeError(\"unable to handle error\")\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    open(\"database.sqlite\")\n"
"    ~~~~^^^^^^^^^^^^^^^^^^^\n"
"FileNotFoundError: [Errno 2] No such file or directory: 'database.sqlite'\n"
"\n"
"During handling of the above exception, another exception occurred:\n"
"\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError(\"unable to handle error\")\n"
"RuntimeError: unable to handle error"
msgstr ""
">>> try:\n"
"...     open(\"base_de_dados.sqlite\")\n"
"... except OSError:\n"
"...     raise RuntimeError(\"incapaz de tratar o erro\")\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    open(\"base_de_dados.sqlite\")\n"
"    ~~~~^^^^^^^^^^^^^^^^^^^^^^^\n"
"FileNotFoundError: [Errno 2] Não existe esse ficheiro ou diretório: "
"'base_de_dados.sqlite'\n"
"\n"
"Durante o tratamento da exceção acima, ocorreu outra exceção:\n"
"\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError(\"incapaz de tratar o erro\")\n"
"RuntimeError: incapaz de tratar o erro"

#: ../../tutorial/errors.rst:317
msgid ""
"To indicate that an exception is a direct consequence of another, the :"
"keyword:`raise` statement allows an optional :keyword:`from<raise>` clause::"
msgstr ""
"Para indicar que uma exceção é uma consequência direta de outra, a "
"instrução :keyword:`raise` permite uma cláusula opcional :keyword:"
"`from<raise>`:"

#: ../../tutorial/errors.rst:320
msgid ""
"# exc must be exception instance or None.\n"
"raise RuntimeError from exc"
msgstr ""
"# exc deve ser uma instância de exceção ou None.\n"
"raise RuntimeError from exc"

#: ../../tutorial/errors.rst:323
msgid "This can be useful when you are transforming exceptions. For example::"
msgstr "Isto pode ser útil quando está a transformar exceções. Por exemplo:"

#: ../../tutorial/errors.rst:325
msgid ""
">>> def func():\n"
"...     raise ConnectionError\n"
"...\n"
">>> try:\n"
"...     func()\n"
"... except ConnectionError as exc:\n"
"...     raise RuntimeError('Failed to open database') from exc\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    func()\n"
"    ~~~~^^\n"
"  File \"<stdin>\", line 2, in func\n"
"ConnectionError\n"
"\n"
"The above exception was the direct cause of the following exception:\n"
"\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError('Failed to open database') from exc\n"
"RuntimeError: Failed to open database"
msgstr ""
">>> def func():\n"
"...     raise ConnectionError\n"
"...\n"
">>> try:\n"
"...     func()\n"
"... except ConnectionError as exc:\n"
"...     raise RuntimeError('Falhou ao abrir a base de dados') from exc\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    func()\n"
"    ~~~~^^\n"
"  File \"<stdin>\", line 2, in func\n"
"ConnectionError\n"
"\n"
"The above exception was the direct cause of the following exception:\n"
"\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError('Falhou ao abrir a base de dados') from exc\n"
"RuntimeError: Falhou ao abrir a base de dados"

#: ../../tutorial/errors.rst:347
msgid ""
"It also allows disabling automatic exception chaining using the ``from "
"None`` idiom::"
msgstr ""
"Também permite desativar o encadeamento automático de exceções usando o "
"idioma ``from None``:"

#: ../../tutorial/errors.rst:350
msgid ""
">>> try:\n"
"...     open('database.sqlite')\n"
"... except OSError:\n"
"...     raise RuntimeError from None\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError from None\n"
"RuntimeError"
msgstr ""
">>> try:\n"
"...     open('base_de_dados.sqlite')\n"
"... except OSError:\n"
"...     raise RuntimeError from None\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 4, in <module>\n"
"    raise RuntimeError from None\n"
"RuntimeError"

#: ../../tutorial/errors.rst:360
msgid ""
"For more information about chaining mechanics, see :ref:`bltin-exceptions`."
msgstr ""
"Para mais informações sobre a mecânica de encadeamento, consulte :ref:`bltin-"
"exceptions`."

#: ../../tutorial/errors.rst:366
msgid "User-defined Exceptions"
msgstr "Exceções definidas pelo utilizador"

#: ../../tutorial/errors.rst:368
msgid ""
"Programs may name their own exceptions by creating a new exception class "
"(see :ref:`tut-classes` for more about Python classes).  Exceptions should "
"typically be derived from the :exc:`Exception` class, either directly or "
"indirectly."
msgstr ""
"Os programas podem nomear as suas próprias exceções criando uma nova classe "
"de exceção (consulte :ref:`tut-classes` para mais informações sobre classes "
"em Python). As exceções devem tipicamente derivar da classe :exc:"
"`Exception`, diretamente ou indiretamente."

#: ../../tutorial/errors.rst:372
msgid ""
"Exception classes can be defined which do anything any other class can do, "
"but are usually kept simple, often only offering a number of attributes that "
"allow information about the error to be extracted by handlers for the "
"exception."
msgstr ""
"As classes de exceção podem ser definidas para fazer qualquer coisa que "
"qualquer outra classe possa fazer, mas geralmente são mantidas simples, "
"oferecendo frequentemente apenas alguns atributos que permitem extrair "
"informações sobre o erro pelos manipuladores da exceção."

#: ../../tutorial/errors.rst:376
msgid ""
"Most exceptions are defined with names that end in \"Error\", similar to the "
"naming of the standard exceptions."
msgstr ""
"A maioria das exceções são definidas com nomes que terminam em \"Error\", "
"semelhante à nomenclatura das exceções padrão."

#: ../../tutorial/errors.rst:379
msgid ""
"Many standard modules define their own exceptions to report errors that may "
"occur in functions they define."
msgstr ""
"Muitos módulos padrão definem as suas próprias exceções para reportar erros "
"que podem ocorrer nas funções que definem."

#: ../../tutorial/errors.rst:386
msgid "Defining Clean-up Actions"
msgstr "Definição de ações de limpeza"

#: ../../tutorial/errors.rst:388
msgid ""
"The :keyword:`try` statement has another optional clause which is intended "
"to define clean-up actions that must be executed under all circumstances.  "
"For example::"
msgstr ""
"A instrução :keyword:`try` tem outra cláusula opcional que destina-se a "
"definir ações de limpeza que devem ser executadas em todas as "
"circunstâncias. Por exemplo:"

#: ../../tutorial/errors.rst:392
msgid ""
">>> try:\n"
"...     raise KeyboardInterrupt\n"
"... finally:\n"
"...     print('Goodbye, world!')\n"
"...\n"
"Goodbye, world!\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise KeyboardInterrupt\n"
"KeyboardInterrupt"
msgstr ""
">>> try:\n"
"...     raise KeyboardInterrupt\n"
"... finally:\n"
"...     print('Adeus, mundo!')\n"
"...\n"
"Adeus, mundo!\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise KeyboardInterrupt\n"
"KeyboardInterrupt"

#: ../../tutorial/errors.rst:403
msgid ""
"If a :keyword:`finally` clause is present, the :keyword:`!finally` clause "
"will execute as the last task before the :keyword:`try` statement completes. "
"The :keyword:`!finally` clause runs whether or not the :keyword:`!try` "
"statement produces an exception. The following points discuss more complex "
"cases when an exception occurs:"
msgstr ""
"Se uma cláusula :keyword:`finally` estiver presente, a cláusula :keyword:`!"
"finally` será executada como a última tarefa antes de a instrução :keyword:"
"`try` ser concluída. A cláusula :keyword:`!finally` é executada "
"independentemente de a instrução :keyword:`!try` produzir ou não uma "
"exceção. Os seguintes pontos discutem casos mais complexos quando ocorre uma "
"exceção:"

#: ../../tutorial/errors.rst:409
msgid ""
"If an exception occurs during execution of the :keyword:`!try` clause, the "
"exception may be handled by an :keyword:`except` clause. If the exception is "
"not handled by an :keyword:`!except` clause, the exception is re-raised "
"after the :keyword:`!finally` clause has been executed."
msgstr ""
"Se uma exceção ocorrer durante a execução da cláusula :keyword:`!try`, a "
"exceção pode ser tratada por uma cláusula :keyword:`except`. Se a exceção "
"não for tratada por uma cláusula :keyword:`!except`, a exceção é relançada "
"após a cláusula :keyword:`!finally` ter sido executada."

#: ../../tutorial/errors.rst:415
msgid ""
"An exception could occur during execution of an :keyword:`!except` or :"
"keyword:`!else` clause. Again, the exception is re-raised after the :keyword:"
"`!finally` clause has been executed."
msgstr ""
"Uma exceção pode ocorrer durante a execução de uma cláusula :keyword:`!"
"except` ou :keyword:`!else`. Novamente, a exceção é relançada após a "
"cláusula :keyword:`!finally` ter sido executada."

#: ../../tutorial/errors.rst:419
msgid ""
"If the :keyword:`!finally` clause executes a :keyword:`break`, :keyword:"
"`continue` or :keyword:`return` statement, exceptions are not re-raised."
msgstr ""

#: ../../tutorial/errors.rst:423
msgid ""
"If the :keyword:`!try` statement reaches a :keyword:`break`, :keyword:"
"`continue` or :keyword:`return` statement, the :keyword:`!finally` clause "
"will execute just prior to the :keyword:`!break`, :keyword:`!continue` or :"
"keyword:`!return` statement's execution."
msgstr ""
"Se a instrução :keyword:`!try` atingir uma instrução :keyword:`break`, :"
"keyword:`continue` ou :keyword:`return`, a cláusula :keyword:`!finally` será "
"executada imediatamente antes da execução da instrução :keyword:`!break`, :"
"keyword:`!continue` ou :keyword:`!return`."

#: ../../tutorial/errors.rst:429
msgid ""
"If a :keyword:`!finally` clause includes a :keyword:`!return` statement, the "
"returned value will be the one from the :keyword:`!finally` clause's :"
"keyword:`!return` statement, not the value from the :keyword:`!try` "
"clause's :keyword:`!return` statement."
msgstr ""

#: ../../tutorial/errors.rst:435
msgid "For example::"
msgstr "Por exemplo::"

#: ../../tutorial/errors.rst:437
msgid ""
">>> def bool_return():\n"
"...     try:\n"
"...         return True\n"
"...     finally:\n"
"...         return False\n"
"...\n"
">>> bool_return()\n"
"False"
msgstr ""
">>> def bool_return():\n"
"...     try:\n"
"...         return True\n"
"...     finally:\n"
"...         return False\n"
"...\n"
">>> bool_return()\n"
"False"

#: ../../tutorial/errors.rst:446
msgid "A more complicated example::"
msgstr "Um exemplo mais complicado:"

#: ../../tutorial/errors.rst:448
msgid ""
">>> def divide(x, y):\n"
"...     try:\n"
"...         result = x / y\n"
"...     except ZeroDivisionError:\n"
"...         print(\"division by zero!\")\n"
"...     else:\n"
"...         print(\"result is\", result)\n"
"...     finally:\n"
"...         print(\"executing finally clause\")\n"
"...\n"
">>> divide(2, 1)\n"
"result is 2.0\n"
"executing finally clause\n"
">>> divide(2, 0)\n"
"division by zero!\n"
"executing finally clause\n"
">>> divide(\"2\", \"1\")\n"
"executing finally clause\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    divide(\"2\", \"1\")\n"
"    ~~~~~~^^^^^^^^^^\n"
"  File \"<stdin>\", line 3, in divide\n"
"    result = x / y\n"
"             ~~^~~\n"
"TypeError: unsupported operand type(s) for /: 'str' and 'str'"
msgstr ""
">>> def divide(x, y):\n"
"...     try:\n"
"...         result = x / y\n"
"...     except ZeroDivisionError:\n"
"...         print(\"divisão por zero!\")\n"
"...     else:\n"
"...         print(\"o resultado é\", result)\n"
"...     finally:\n"
"...         print(\"a executar a cláusula finally\")\n"
"...\n"
">>> divide(2, 1)\n"
"o resultado é 2,0\n"
"a executar a cláusula finally\n"
">>> divide(2, 0)\n"
"divisão por zero!\n"
"a executar a cláusula finally\n"
">>> divide(\"2\", \"1\")\n"
"a executar a cláusula finally\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 1, in <module>\n"
"    divide(\"2\", \"1\")\n"
"    ~~~~~~^^^^^^^^^^\n"
"  File \"<stdin>\", line 3, in divide\n"
"    result = x / y\n"
"             ~~^~~\n"
"TypeError: tipo(s) de operando não suportado(s) para /: 'str' e 'str'"

#: ../../tutorial/errors.rst:475
msgid ""
"As you can see, the :keyword:`finally` clause is executed in any event.  "
"The :exc:`TypeError` raised by dividing two strings is not handled by the :"
"keyword:`except` clause and therefore re-raised after the :keyword:`!"
"finally` clause has been executed."
msgstr ""
"Como pode ver, a cláusula :keyword:`finally` é executada em qualquer evento. "
"O :exc:`TypeError` levantado pela divisão de duas strings não é tratado pela "
"cláusula :keyword:`except` e, por isso, é relançado após a execução da "
"cláusula :keyword:`!finally`."

#: ../../tutorial/errors.rst:480
msgid ""
"In real world applications, the :keyword:`finally` clause is useful for "
"releasing external resources (such as files or network connections), "
"regardless of whether the use of the resource was successful."
msgstr ""
"Em aplicações do mundo real, a cláusula :keyword:`finally` é útil para "
"libertar recursos externos (como ficheiros ou ligações de rede), "
"independentemente de a utilização do recurso ter sido bem-sucedida."

#: ../../tutorial/errors.rst:488
msgid "Predefined Clean-up Actions"
msgstr "Ações de limpeza predefinidas"

#: ../../tutorial/errors.rst:490
msgid ""
"Some objects define standard clean-up actions to be undertaken when the "
"object is no longer needed, regardless of whether or not the operation using "
"the object succeeded or failed. Look at the following example, which tries "
"to open a file and print its contents to the screen. ::"
msgstr ""
"Alguns objetos definem ações de limpeza padrão a serem executadas quando o "
"objeto já não é necessário, independentemente de a operação que usa o objeto "
"ter sido bem-sucedida ou não. Veja o seguinte exemplo, que tenta abrir um "
"ficheiro e imprimir o seu conteúdo no ecrã:"

#: ../../tutorial/errors.rst:495
msgid ""
"for line in open(\"myfile.txt\"):\n"
"    print(line, end=\"\")"
msgstr ""
"for line in open(\"meuficheiro.txt\"):\n"
"    print(line, end=\"\")"

#: ../../tutorial/errors.rst:498
msgid ""
"The problem with this code is that it leaves the file open for an "
"indeterminate amount of time after this part of the code has finished "
"executing. This is not an issue in simple scripts, but can be a problem for "
"larger applications. The :keyword:`with` statement allows objects like files "
"to be used in a way that ensures they are always cleaned up promptly and "
"correctly. ::"
msgstr ""
"O problema com este código é que deixa o ficheiro aberto por um período de "
"tempo indeterminado após esta parte do código ter terminado a execução. Isto "
"não é um problema em scripts simples, mas pode ser um problema para "
"aplicações maiores. A instrução :keyword:`with` permite que objetos como "
"ficheiros sejam usados de uma forma que garante que são sempre limpos "
"prontamente e corretamente:"

#: ../../tutorial/errors.rst:504
msgid ""
"with open(\"myfile.txt\") as f:\n"
"    for line in f:\n"
"        print(line, end=\"\")"
msgstr ""
"with open(\"meuficheiro.txt\") as f:\n"
"    for line in f:\n"
"        print(line, end=\"\")"

#: ../../tutorial/errors.rst:508
msgid ""
"After the statement is executed, the file *f* is always closed, even if a "
"problem was encountered while processing the lines. Objects which, like "
"files, provide predefined clean-up actions will indicate this in their "
"documentation."
msgstr ""
"Após a execução da instrução, o ficheiro *f* é sempre fechado, mesmo que "
"tenha ocorrido um problema durante o processamento das linhas. Objetos que, "
"como os ficheiros, fornecem ações de limpeza predefinidas, indicarão isso na "
"sua documentação."

#: ../../tutorial/errors.rst:516
msgid "Raising and Handling Multiple Unrelated Exceptions"
msgstr "Lançamento e tratamento de múltiplas exceções não relacionadas"

#: ../../tutorial/errors.rst:518
msgid ""
"There are situations where it is necessary to report several exceptions that "
"have occurred. This is often the case in concurrency frameworks, when "
"several tasks may have failed in parallel, but there are also other use "
"cases where it is desirable to continue execution and collect multiple "
"errors rather than raise the first exception."
msgstr ""
"Existem situações em que é necessário reportar várias exceções que "
"ocorreram. Isto é muitas vezes o caso em frameworks de concorrência, quando "
"várias tarefas podem ter falhado em paralelo, mas também existem outros "
"casos de uso em que é desejável continuar a execução e recolher múltiplos "
"erros em vez de lançar a primeira exceção."

#: ../../tutorial/errors.rst:524
msgid ""
"The builtin :exc:`ExceptionGroup` wraps a list of exception instances so "
"that they can be raised together. It is an exception itself, so it can be "
"caught like any other exception. ::"
msgstr ""
"A classe incorporada :exc:`ExceptionGroup` envolve uma lista de instâncias "
"de exceção para que possam ser lançadas em conjunto. É ela própria uma "
"exceção, por isso pode ser capturada como qualquer outra exceção:"

#: ../../tutorial/errors.rst:528
msgid ""
">>> def f():\n"
"...     excs = [OSError('error 1'), SystemError('error 2')]\n"
"...     raise ExceptionGroup('there were problems', excs)\n"
"...\n"
">>> f()\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 1, in <module>\n"
"  |     f()\n"
"  |     ~^^\n"
"  |   File \"<stdin>\", line 3, in f\n"
"  |     raise ExceptionGroup('there were problems', excs)\n"
"  | ExceptionGroup: there were problems (2 sub-exceptions)\n"
"  +-+---------------- 1 ----------------\n"
"    | OSError: error 1\n"
"    +---------------- 2 ----------------\n"
"    | SystemError: error 2\n"
"    +------------------------------------\n"
">>> try:\n"
"...     f()\n"
"... except Exception as e:\n"
"...     print(f'caught {type(e)}: e')\n"
"...\n"
"caught <class 'ExceptionGroup'>: e\n"
">>>"
msgstr ""
">>> def f():\n"
"...     excs = [OSError('erro 1'), SystemError('erro 2')]\n"
"...     raise ExceptionGroup('houve problemas', excs)\n"
"...\n"
">>> f()\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 1, in <module>\n"
"  |     f()\n"
"  |     ~^^\n"
"  |   File \"<stdin>\", line 3, in f\n"
"  |     raise ExceptionGroup('houve problemas', excs)\n"
"  | ExceptionGroup: houve problemas (2 sub-exceções)\n"
"  +-+---------------- 1 ----------------\n"
"    | OSError: erro 1\n"
"    +---------------- 2 ----------------\n"
"    | SystemError: erro 2\n"
"    +------------------------------------\n"
">>> try:\n"
"...     f()\n"
"... except Exception as e:\n"
"...     print(f'capturada {type(e)}: e')\n"
"...\n"
"capturada <class 'ExceptionGroup'>: e\n"
">>>"

#: ../../tutorial/errors.rst:553
msgid ""
"By using ``except*`` instead of ``except``, we can selectively handle only "
"the exceptions in the group that match a certain type. In the following "
"example, which shows a nested exception group, each ``except*`` clause "
"extracts from the group exceptions of a certain type while letting all other "
"exceptions propagate to other clauses and eventually to be reraised. ::"
msgstr ""
"Ao usar ``except*`` em vez de ``except``, podemos tratar seletivamente "
"apenas as exceções no grupo que correspondem a um certo tipo. No exemplo "
"seguinte, que mostra um grupo de exceções aninhado, cada cláusula "
"``except*`` extrai do grupo exceções de um certo tipo, permitindo que todas "
"as outras exceções se propaguem para outras cláusulas e, eventualmente, "
"sejam relançadas:"

#: ../../tutorial/errors.rst:560
msgid ""
">>> def f():\n"
"...     raise ExceptionGroup(\n"
"...         \"group1\",\n"
"...         [\n"
"...             OSError(1),\n"
"...             SystemError(2),\n"
"...             ExceptionGroup(\n"
"...                 \"group2\",\n"
"...                 [\n"
"...                     OSError(3),\n"
"...                     RecursionError(4)\n"
"...                 ]\n"
"...             )\n"
"...         ]\n"
"...     )\n"
"...\n"
">>> try:\n"
"...     f()\n"
"... except* OSError as e:\n"
"...     print(\"There were OSErrors\")\n"
"... except* SystemError as e:\n"
"...     print(\"There were SystemErrors\")\n"
"...\n"
"There were OSErrors\n"
"There were SystemErrors\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 2, in <module>\n"
"  |     f()\n"
"  |     ~^^\n"
"  |   File \"<stdin>\", line 2, in f\n"
"  |     raise ExceptionGroup(\n"
"  |     ...<12 lines>...\n"
"  |     )\n"
"  | ExceptionGroup: group1 (1 sub-exception)\n"
"  +-+---------------- 1 ----------------\n"
"    | ExceptionGroup: group2 (1 sub-exception)\n"
"    +-+---------------- 1 ----------------\n"
"      | RecursionError: 4\n"
"      +------------------------------------\n"
">>>"
msgstr ""
">>> def f():\n"
"...     raise ExceptionGroup(\n"
"...         \"grupo1\",\n"
"...         [\n"
"...             OSError(1),\n"
"...             SystemError(2),\n"
"...             ExceptionGroup(\n"
"...                 \"grupo2\",\n"
"...                 [\n"
"...                     OSError(3),\n"
"...                     RecursionError(4)\n"
"...                 ]\n"
"...             )\n"
"...         ]\n"
"...     )\n"
"...\n"
">>> try:\n"
"...     f()\n"
"... except* OSError as e:\n"
"...     print(\"Houve erros de SO\")\n"
"... except* SystemError as e:\n"
"...     print(\"Houve erros de sistema\")\n"
"...\n"
"Houve erros de SO\n"
"Houve erros de sistema\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 2, in <module>\n"
"  |     f()\n"
"  |     ~^^\n"
"  |   File \"<stdin>\", line 2, in f\n"
"  |     raise ExceptionGroup(\n"
"  |     ...<12 lines>...\n"
"  |     )\n"
"  | ExceptionGroup: grupo1 (1 sub-exceção)\n"
"  +-+---------------- 1 ----------------\n"
"    | ExceptionGroup: grupo2 (1 sub-exceção)\n"
"    +-+---------------- 1 ----------------\n"
"      | RecursionError: 4\n"
"      +------------------------------------\n"
">>>"

#: ../../tutorial/errors.rst:601
msgid ""
"Note that the exceptions nested in an exception group must be instances, not "
"types. This is because in practice the exceptions would typically be ones "
"that have already been raised and caught by the program, along the following "
"pattern::"
msgstr ""
"Note que as exceções aninhadas num grupo de exceções devem ser instâncias, "
"não tipos. Isto porque, na prática, as exceções seriam tipicamente aquelas "
"que já foram lançadas e capturadas pelo programa, de acordo com o seguinte "
"padrão:"

#: ../../tutorial/errors.rst:606
msgid ""
">>> excs = []\n"
"... for test in tests:\n"
"...     try:\n"
"...         test.run()\n"
"...     except Exception as e:\n"
"...         excs.append(e)\n"
"...\n"
">>> if excs:\n"
"...    raise ExceptionGroup(\"Test Failures\", excs)\n"
"..."
msgstr ""
">>> excs = []\n"
"... for test in tests:\n"
"...     try:\n"
"...         test.run()\n"
"...     except Exception as e:\n"
"...         excs.append(e)\n"
"...\n"
">>> if excs:\n"
"...    raise ExceptionGroup(\"Falhas nos testes\", excs)\n"
"..."

#: ../../tutorial/errors.rst:621
msgid "Enriching Exceptions with Notes"
msgstr "Enriquecer exceções com notas"

#: ../../tutorial/errors.rst:623
msgid ""
"When an exception is created in order to be raised, it is usually "
"initialized with information that describes the error that has occurred. "
"There are cases where it is useful to add information after the exception "
"was caught. For this purpose, exceptions have a method ``add_note(note)`` "
"that accepts a string and adds it to the exception's notes list. The "
"standard traceback rendering includes all notes, in the order they were "
"added, after the exception. ::"
msgstr ""
"Quando uma exceção é criada para ser lançada, é geralmente inicializada com "
"informações que descrevem o erro que ocorreu. Existem casos em que é útil "
"adicionar informações após a exceção ter sido capturada. Para este fim, as "
"exceções têm um método ``add_note(nota)`` que aceita uma string e a adiciona "
"à lista de notas da exceção. A apresentação padrão do rastreio inclui todas "
"as notas, pela ordem em que foram adicionadas, após a exceção:"

#: ../../tutorial/errors.rst:630
msgid ""
">>> try:\n"
"...     raise TypeError('bad type')\n"
"... except Exception as e:\n"
"...     e.add_note('Add some information')\n"
"...     e.add_note('Add some more information')\n"
"...     raise\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise TypeError('bad type')\n"
"TypeError: bad type\n"
"Add some information\n"
"Add some more information\n"
">>>"
msgstr ""
">>> try:\n"
"...     raise TypeError('tipo inválido')\n"
"... except Exception as e:\n"
"...     e.add_note('Adicionar alguma informação')\n"
"...     e.add_note('Adicionar mais alguma informação')\n"
"...     raise\n"
"...\n"
"Traceback (most recent call last):\n"
"  File \"<stdin>\", line 2, in <module>\n"
"    raise TypeError('tipo inválido')\n"
"TypeError: tipo inválido\n"
"Adicionar alguma informação\n"
"Adicionar mais alguma informação\n"
">>>"

#: ../../tutorial/errors.rst:645
msgid ""
"For example, when collecting exceptions into an exception group, we may want "
"to add context information for the individual errors. In the following each "
"exception in the group has a note indicating when this error has occurred. ::"
msgstr ""
"Por exemplo, ao recolher exceções num grupo de exceções, podemos querer "
"adicionar informações de contexto para os erros individuais. No seguinte "
"exemplo, cada exceção no grupo tem uma nota indicando quando este erro "
"ocorreu:"

#: ../../tutorial/errors.rst:649
msgid ""
">>> def f():\n"
"...     raise OSError('operation failed')\n"
"...\n"
">>> excs = []\n"
">>> for i in range(3):\n"
"...     try:\n"
"...         f()\n"
"...     except Exception as e:\n"
"...         e.add_note(f'Happened in Iteration {i+1}')\n"
"...         excs.append(e)\n"
"...\n"
">>> raise ExceptionGroup('We have some problems', excs)\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 1, in <module>\n"
"  |     raise ExceptionGroup('We have some problems', excs)\n"
"  | ExceptionGroup: We have some problems (3 sub-exceptions)\n"
"  +-+---------------- 1 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operation failed')\n"
"    | OSError: operation failed\n"
"    | Happened in Iteration 1\n"
"    +---------------- 2 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operation failed')\n"
"    | OSError: operation failed\n"
"    | Happened in Iteration 2\n"
"    +---------------- 3 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operation failed')\n"
"    | OSError: operation failed\n"
"    | Happened in Iteration 3\n"
"    +------------------------------------\n"
">>>"
msgstr ""
">>> def f():\n"
"...     raise OSError('operação falhou')\n"
"...\n"
">>> excs = []\n"
">>> for i in range(3):\n"
"...     try:\n"
"...         f()\n"
"...     except Exception as e:\n"
"...         e.add_note(f'Ocorreu na iteração {i+1}')\n"
"...         excs.append(e)\n"
"...\n"
">>> raise ExceptionGroup('Temos alguns problemas', excs)\n"
"  + Exception Group Traceback (most recent call last):\n"
"  |   File \"<stdin>\", line 1, in <module>\n"
"  |     raise ExceptionGroup('Temos alguns problemas', excs)\n"
"  | ExceptionGroup: Temos alguns problemas (3 sub-exceções)\n"
"  +-+---------------- 1 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operação falhou')\n"
"    | OSError: operação falhou\n"
"    | Ocorreu na iteração 1\n"
"    +---------------- 2 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operação falhou')\n"
"    | OSError: operação falhou\n"
"    | Ocorreu na iteração 2\n"
"    +---------------- 3 ----------------\n"
"    | Traceback (most recent call last):\n"
"    |   File \"<stdin>\", line 3, in <module>\n"
"    |     f()\n"
"    |     ~^^\n"
"    |   File \"<stdin>\", line 2, in f\n"
"    |     raise OSError('operação falhou')\n"
"    | OSError: operação falhou\n"
"    | Ocorreu na iteração 3\n"
"    +------------------------------------\n"
">>>"
