# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# python-doc bot, 2025
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.11\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-17 16:35+0000\n"
"PO-Revision-Date: 2025-09-22 16:51+0000\n"
"Last-Translator: python-doc bot, 2025\n"
"Language-Team: Swedish (https://app.transifex.com/python-doc/teams/5390/"
"sv/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: sv\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../../tutorial/errors.rst:5
msgid "Errors and Exceptions"
msgstr "Fel och undantag"

#: ../../tutorial/errors.rst:7
msgid ""
"Until now error messages haven't been more than mentioned, but if you have "
"tried out the examples you have probably seen some.  There are (at least) "
"two distinguishable kinds of errors: *syntax errors* and *exceptions*."
msgstr ""
"Hittills har felmeddelanden inte mer än nämnts, men om du har provat "
"exemplen har du förmodligen sett några.  Det finns (minst) två typer av fel "
"som kan särskiljas: *syntaxfel* och *undantag*."

#: ../../tutorial/errors.rst:15
msgid "Syntax Errors"
msgstr "Syntaxfel"

#: ../../tutorial/errors.rst:17
msgid ""
"Syntax errors, also known as parsing errors, are perhaps the most common "
"kind of complaint you get while you are still learning Python::"
msgstr ""
"Syntaxfel, även kända som parsingfel, är kanske den vanligaste typen av "
"klagomål du får medan du fortfarande lär dig Python::"

#: ../../tutorial/errors.rst:26
msgid ""
"The parser repeats the offending line and displays little 'arrow's pointing "
"at the token in the line where the error was detected.  The error may be "
"caused by the absence of a token *before* the indicated token.  In the "
"example, the error is detected at the function :func:`print`, since a colon "
"(``':'``) is missing before it.  File name and line number are printed so "
"you know where to look in case the input came from a script."
msgstr ""

#: ../../tutorial/errors.rst:37
msgid "Exceptions"
msgstr "Undantag"

#: ../../tutorial/errors.rst:39
msgid ""
"Even if a statement or expression is syntactically correct, it may cause an "
"error when an attempt is made to execute it. Errors detected during "
"execution are called *exceptions* and are not unconditionally fatal: you "
"will soon learn how to handle them in Python programs.  Most exceptions are "
"not handled by programs, however, and result in error messages as shown "
"here::"
msgstr ""
"Även om en sats eller ett uttryck är syntaktiskt korrekt kan det orsaka ett "
"fel när man försöker exekvera det. Fel som upptäcks under exekveringen "
"kallas *undantag* och är inte ovillkorligen fatala: du kommer snart att lära "
"dig hur du hanterar dem i Python-program.  De flesta undantag hanteras dock "
"inte av program, utan resulterar i felmeddelanden som visas här::"

#: ../../tutorial/errors.rst:58
msgid ""
"The last line of the error message indicates what happened. Exceptions come "
"in different types, and the type is printed as part of the message: the "
"types in the example are :exc:`ZeroDivisionError`, :exc:`NameError` and :exc:"
"`TypeError`. The string printed as the exception type is the name of the "
"built-in exception that occurred.  This is true for all built-in exceptions, "
"but need not be true for user-defined exceptions (although it is a useful "
"convention). Standard exception names are built-in identifiers (not reserved "
"keywords)."
msgstr ""
"Den sista raden i felmeddelandet anger vad som hände. Undantag finns i olika "
"typer och typen skrivs ut som en del av meddelandet: typerna i exemplet är :"
"exc:`ZeroDivisionError`, :exc:`NameError` och :exc:`TypeError`. Den sträng "
"som skrivs ut som undantagstyp är namnet på det inbyggda undantag som "
"inträffade.  Detta gäller för alla inbyggda undantag, men behöver inte gälla "
"för användardefinierade undantag (även om det är en användbar konvention). "
"Standardnamn på undantag är inbyggda identifierare (inte reserverade "
"nyckelord)."

#: ../../tutorial/errors.rst:66
msgid ""
"The rest of the line provides detail based on the type of exception and what "
"caused it."
msgstr ""
"Resten av raden innehåller detaljer som baseras på typen av undantag och vad "
"som orsakade det."

#: ../../tutorial/errors.rst:69
msgid ""
"The preceding part of the error message shows the context where the "
"exception occurred, in the form of a stack traceback. In general it contains "
"a stack traceback listing source lines; however, it will not display lines "
"read from standard input."
msgstr ""
"Den föregående delen av felmeddelandet visar det sammanhang där undantaget "
"inträffade, i form av en stack traceback. I allmänhet innehåller det en "
"stack traceback som listar källrader, men det kommer inte att visa rader som "
"läses från standardinmatningen."

#: ../../tutorial/errors.rst:74
msgid ""
":ref:`bltin-exceptions` lists the built-in exceptions and their meanings."
msgstr ""
":ref:`bltin-exceptions` listar de inbyggda undantagen och deras innebörd."

#: ../../tutorial/errors.rst:80
msgid "Handling Exceptions"
msgstr "Hantering av undantag"

#: ../../tutorial/errors.rst:82
msgid ""
"It is possible to write programs that handle selected exceptions. Look at "
"the following example, which asks the user for input until a valid integer "
"has been entered, but allows the user to interrupt the program (using :kbd:"
"`Control-C` or whatever the operating system supports); note that a user-"
"generated interruption is signalled by raising the :exc:`KeyboardInterrupt` "
"exception. ::"
msgstr ""
"Det är möjligt att skriva program som hanterar utvalda undantag. Titta på "
"följande exempel, som ber användaren om inmatning tills ett giltigt heltal "
"har matats in, men tillåter användaren att avbryta programmet (med hjälp av :"
"kbd:`Control-C` eller vad operativsystemet stöder); notera att ett "
"användargenererat avbrott signaleras genom att lyfta :exc:"
"`KeyboardInterrupt` undantaget. ::"

#: ../../tutorial/errors.rst:96
msgid "The :keyword:`try` statement works as follows."
msgstr "Satsen :keyword:`try` fungerar på följande sätt."

#: ../../tutorial/errors.rst:98
msgid ""
"First, the *try clause* (the statement(s) between the :keyword:`try` and :"
"keyword:`except` keywords) is executed."
msgstr ""
"Först utförs *försöksklausulen* (satsen eller satserna mellan nyckelorden :"
"keyword:`try` och :keyword:`except`)."

#: ../../tutorial/errors.rst:101
msgid ""
"If no exception occurs, the *except clause* is skipped and execution of the :"
"keyword:`try` statement is finished."
msgstr ""
"Om inget undantag inträffar hoppas *except-klausulen* över och körningen av :"
"keyword:`try`\\-satsen avslutas."

#: ../../tutorial/errors.rst:104
msgid ""
"If an exception occurs during execution of the :keyword:`try` clause, the "
"rest of the clause is skipped.  Then, if its type matches the exception "
"named after the :keyword:`except` keyword, the *except clause* is executed, "
"and then execution continues after the try/except block."
msgstr ""
"Om ett undantag inträffar under exekveringen av :keyword:`try`\\-satsen, "
"hoppas resten av satsen över.  Om dess typ matchar undantaget som anges "
"efter nyckelordet :keyword:`except`, exekveras *except-satsen*, och sedan "
"fortsätter exekveringen efter try/except-blocket."

#: ../../tutorial/errors.rst:109
msgid ""
"If an exception occurs which does not match the exception named in the "
"*except clause*, it is passed on to outer :keyword:`try` statements; if no "
"handler is found, it is an *unhandled exception* and execution stops with an "
"error message."
msgstr ""
"Om ett undantag inträffar som inte stämmer överens med undantaget som anges "
"i *except-satsen*, skickas det vidare till yttre :keyword:`try`\\-satser; om "
"ingen hanterare hittas är det ett *ohanterat undantag* och exekveringen "
"stoppas med ett felmeddelande."

#: ../../tutorial/errors.rst:113
msgid ""
"A :keyword:`try` statement may have more than one *except clause*, to "
"specify handlers for different exceptions.  At most one handler will be "
"executed. Handlers only handle exceptions that occur in the corresponding "
"*try clause*, not in other handlers of the same :keyword:`!try` statement.  "
"An *except clause* may name multiple exceptions as a parenthesized tuple, "
"for example::"
msgstr ""
"En :keyword:`try`\\-sats kan ha mer än en *except-klausul* för att ange "
"hanterare för olika undantag.  Högst en hanterare kommer att exekveras. "
"Hanterarna hanterar bara undantag som förekommer i motsvarande *try-sats*, "
"inte i andra hanterare av samma :keyword:`!try`\\-sats.  En *except-sats* "
"kan namnge flera undantag som en parentesförsedd tupel, till exempel::"

#: ../../tutorial/errors.rst:122
msgid ""
"A class in an :keyword:`except` clause is compatible with an exception if it "
"is the same class or a base class thereof (but not the other way around --- "
"an *except clause* listing a derived class is not compatible with a base "
"class). For example, the following code will print B, C, D in that order::"
msgstr ""

#: ../../tutorial/errors.rst:146
msgid ""
"Note that if the *except clauses* were reversed (with ``except B`` first), "
"it would have printed B, B, B --- the first matching *except clause* is "
"triggered."
msgstr ""
"Observera att om *except-klausulerna* hade varit omvända (med ``except B`` "
"först), skulle det ha skrivit ut B, B, B --- den första matchande *except-"
"klausulen* utlöses."

#: ../../tutorial/errors.rst:149
msgid ""
"When an exception occurs, it may have associated values, also known as the "
"exception's *arguments*. The presence and types of the arguments depend on "
"the exception type."
msgstr ""
"När ett undantag inträffar kan det ha associerade värden, även kallade "
"undantagets *argument*. Vilka argument som finns och vilka typer av argument "
"som finns beror på undantagstypen."

#: ../../tutorial/errors.rst:153
msgid ""
"The *except clause* may specify a variable after the exception name.  The "
"variable is bound to the exception instance which typically has an ``args`` "
"attribute that stores the arguments. For convenience, builtin exception "
"types define :meth:`~object.__str__` to print all the arguments without "
"explicitly accessing ``.args``.  ::"
msgstr ""
"*except-klausulen* kan ange en variabel efter undantagsnamnet. Variabeln är "
"bunden till undantagsinstansen som vanligtvis har ett ``args``\\-attribut "
"som lagrar argumenten. För enkelhetens skull definierar inbyggda "
"undantagstyper :meth:`~object.__str__` för att skriva ut alla argument utan "
"att uttryckligen komma åt ``.args``. ::"

#: ../../tutorial/errors.rst:176
msgid ""
"The exception's :meth:`~object.__str__` output is printed as the last part "
"('detail') of the message for unhandled exceptions."
msgstr ""
"Undantagets :meth:`~object.__str__`\\-utdata skrivs ut som den sista delen "
"(\"detail\") av meddelandet för ohanterade undantag."

#: ../../tutorial/errors.rst:179
msgid ""
":exc:`BaseException` is the common base class of all exceptions. One of its "
"subclasses, :exc:`Exception`, is the base class of all the non-fatal "
"exceptions. Exceptions which are not subclasses of :exc:`Exception` are not "
"typically handled, because they are used to indicate that the program should "
"terminate. They include :exc:`SystemExit` which is raised by :meth:`sys."
"exit` and :exc:`KeyboardInterrupt` which is raised when a user wishes to "
"interrupt the program."
msgstr ""
":exc:`BaseException` är den gemensamma basklassen för alla undantag. En av "
"dess underklasser, :exc:`Exception`, är basklassen för alla icke-fatal "
"undantag. Undantag som inte är underklasser till :exc:`Exception` hanteras "
"normalt inte, eftersom de används för att ange att programmet ska avslutas. "
"De inkluderar :exc:`SystemExit` som utlöses av :meth:`sys.exit` och :exc:"
"`KeyboardInterrupt` som utlöses när en användare vill avbryta programmet."

#: ../../tutorial/errors.rst:187
msgid ""
":exc:`Exception` can be used as a wildcard that catches (almost) everything. "
"However, it is good practice to be as specific as possible with the types of "
"exceptions that we intend to handle, and to allow any unexpected exceptions "
"to propagate on."
msgstr ""
":exc:`Exception` kan användas som ett jokertecken som fångar upp (nästan) "
"allt. Det är dock god praxis att vara så specifik som möjligt med de typer "
"av undantag som vi avser att hantera, och att låta oväntade undantag sprida "
"sig vidare."

#: ../../tutorial/errors.rst:192
msgid ""
"The most common pattern for handling :exc:`Exception` is to print or log the "
"exception and then re-raise it (allowing a caller to handle the exception as "
"well)::"
msgstr ""
"Det vanligaste mönstret för att hantera :exc:`Exception` är att skriva ut "
"eller logga undantaget och sedan höja det igen (så att en anropare också kan "
"hantera undantaget)::"

#: ../../tutorial/errors.rst:210
msgid ""
"The :keyword:`try` ... :keyword:`except` statement has an optional *else "
"clause*, which, when present, must follow all *except clauses*.  It is "
"useful for code that must be executed if the *try clause* does not raise an "
"exception. For example::"
msgstr ""
"Satsen :keyword:`try` ... :keyword:`except` har en valfri *else-klausul* "
"som, när den finns, måste följa efter alla *except-klausuler*.  Den är "
"användbar för kod som måste köras om *try-satsen* inte ger upphov till ett "
"undantag. Till exempel::"

#: ../../tutorial/errors.rst:224
msgid ""
"The use of the :keyword:`!else` clause is better than adding additional code "
"to the :keyword:`try` clause because it avoids accidentally catching an "
"exception that wasn't raised by the code being protected by the :keyword:`!"
"try` ... :keyword:`!except` statement."
msgstr ""
"Användningen av :keyword:`!else`\\-satsen är bättre än att lägga till "
"ytterligare kod till :keyword:`try`\\-satsen eftersom den undviker att av "
"misstag fånga ett undantag som inte uppstod av koden som skyddas av :keyword:"
"`!try` ... :keyword:`!except`\\-satsen."

#: ../../tutorial/errors.rst:229
msgid ""
"Exception handlers do not handle only exceptions that occur immediately in "
"the *try clause*, but also those that occur inside functions that are called "
"(even indirectly) in the *try clause*. For example::"
msgstr ""
"Undantagshanterare hanterar inte bara undantag som inträffar direkt i "
"*försökssatsen*, utan även de som inträffar inuti funktioner som anropas "
"(även indirekt) i *försökssatsen*. Till exempel::"

#: ../../tutorial/errors.rst:247
msgid "Raising Exceptions"
msgstr "Utredning av undantag"

#: ../../tutorial/errors.rst:249
msgid ""
"The :keyword:`raise` statement allows the programmer to force a specified "
"exception to occur. For example::"
msgstr ""
"Med :keyword:`raise` kan programmeraren tvinga ett specificerat undantag att "
"inträffa. Till exempel::"

#: ../../tutorial/errors.rst:257
msgid ""
"The sole argument to :keyword:`raise` indicates the exception to be raised. "
"This must be either an exception instance or an exception class (a class "
"that derives from :class:`BaseException`, such as :exc:`Exception` or one of "
"its subclasses).  If an exception class is passed, it will be implicitly "
"instantiated by calling its constructor with no arguments::"
msgstr ""
"Det enda argumentet till :keyword:`raise` anger det undantag som skall tas "
"upp. Detta måste vara antingen en undantagsinstans eller en undantagsklass "
"(en klass som härstammar från :class:`BaseException`, t.ex. :exc:`Exception` "
"eller en av dess underklasser).  Om en undantagsklass skickas, kommer den "
"att instansieras implicit genom att anropa dess konstruktör utan argument::"

#: ../../tutorial/errors.rst:265
msgid ""
"If you need to determine whether an exception was raised but don't intend to "
"handle it, a simpler form of the :keyword:`raise` statement allows you to re-"
"raise the exception::"
msgstr ""
"Om du behöver avgöra om ett undantag har uppstått, men inte tänker hantera "
"det, kan du använda en enklare form av :keyword:`raise` för att upprepa "
"undantaget::"

#: ../../tutorial/errors.rst:284
msgid "Exception Chaining"
msgstr "Kedjning av undantag"

#: ../../tutorial/errors.rst:286
msgid ""
"If an unhandled exception occurs inside an :keyword:`except` section, it "
"will have the exception being handled attached to it and included in the "
"error message::"
msgstr ""
"Om ett ohanterat undantag inträffar i ett avsnitt med :keyword:`except`, "
"kommer det undantag som hanteras att kopplas till det och inkluderas i "
"felmeddelandet::"

#: ../../tutorial/errors.rst:305
msgid ""
"To indicate that an exception is a direct consequence of another, the :"
"keyword:`raise` statement allows an optional :keyword:`from<raise>` clause::"
msgstr ""
"För att indikera att ett undantag är en direkt följd av ett annat, tillåter :"
"keyword:`raise`\\-satsen en valfri :keyword:`from<raise>`\\-klausul::"

#: ../../tutorial/errors.rst:311
msgid "This can be useful when you are transforming exceptions. For example::"
msgstr ""
"Detta kan vara användbart när du transformerar undantag. Till exempel::"

#: ../../tutorial/errors.rst:332
msgid ""
"It also allows disabling automatic exception chaining using the ``from "
"None`` idiom::"
msgstr ""
"Det gör det också möjligt att inaktivera automatisk undantagskedja med hjälp "
"av idiomet ``from None``::"

#: ../../tutorial/errors.rst:344
msgid ""
"For more information about chaining mechanics, see :ref:`bltin-exceptions`."
msgstr "För mer information om kedjemekanik, se :ref:`bltin-exceptions`."

#: ../../tutorial/errors.rst:350
msgid "User-defined Exceptions"
msgstr "Användardefinierade undantag"

#: ../../tutorial/errors.rst:352
msgid ""
"Programs may name their own exceptions by creating a new exception class "
"(see :ref:`tut-classes` for more about Python classes).  Exceptions should "
"typically be derived from the :exc:`Exception` class, either directly or "
"indirectly."
msgstr ""
"Program kan namnge sina egna undantag genom att skapa en ny undantagsklass "
"(se :ref:`tut-classes` för mer information om Python-klasser).  Undantag bör "
"typiskt härledas från klassen :exc:`Exception`, antingen direkt eller "
"indirekt."

#: ../../tutorial/errors.rst:356
msgid ""
"Exception classes can be defined which do anything any other class can do, "
"but are usually kept simple, often only offering a number of attributes that "
"allow information about the error to be extracted by handlers for the "
"exception."
msgstr ""
"Undantagsklasser kan definieras som gör allt som andra klasser kan göra, men "
"de är vanligtvis enkla och erbjuder ofta bara ett antal attribut som gör att "
"information om felet kan extraheras av hanterare för undantaget."

#: ../../tutorial/errors.rst:360
msgid ""
"Most exceptions are defined with names that end in \"Error\", similar to the "
"naming of the standard exceptions."
msgstr ""
"De flesta undantag definieras med namn som slutar på \"Error\", vilket "
"liknar namngivningen av standardundantagen."

#: ../../tutorial/errors.rst:363
msgid ""
"Many standard modules define their own exceptions to report errors that may "
"occur in functions they define."
msgstr ""
"Många standardmoduler definierar sina egna undantag för att rapportera fel "
"som kan uppstå i funktioner som de definierar."

#: ../../tutorial/errors.rst:370
msgid "Defining Clean-up Actions"
msgstr "Definiera saneringsåtgärder"

#: ../../tutorial/errors.rst:372
msgid ""
"The :keyword:`try` statement has another optional clause which is intended "
"to define clean-up actions that must be executed under all circumstances.  "
"For example::"
msgstr ""
"Satsen :keyword:`try` har en annan valfri klausul som är avsedd att "
"definiera rensningsåtgärder som måste utföras under alla omständigheter.  "
"Till exempel::"

#: ../../tutorial/errors.rst:386
msgid ""
"If a :keyword:`finally` clause is present, the :keyword:`!finally` clause "
"will execute as the last task before the :keyword:`try` statement completes. "
"The :keyword:`!finally` clause runs whether or not the :keyword:`!try` "
"statement produces an exception. The following points discuss more complex "
"cases when an exception occurs:"
msgstr ""
"Om en :keyword:`finally`\\-klausul finns, kommer :keyword:`!finally`\\-"
"klausulen att utföras som den sista uppgiften innan :keyword:`try`\\-satsen "
"avslutas. Klausulen :keyword:`!finally` körs oavsett om satsen :keyword:`!"
"try` ger upphov till ett undantag eller inte. I följande punkter diskuteras "
"mer komplexa fall när ett undantag inträffar:"

#: ../../tutorial/errors.rst:392
msgid ""
"If an exception occurs during execution of the :keyword:`!try` clause, the "
"exception may be handled by an :keyword:`except` clause. If the exception is "
"not handled by an :keyword:`!except` clause, the exception is re-raised "
"after the :keyword:`!finally` clause has been executed."
msgstr ""
"Om ett undantag inträffar under exekveringen av :keyword:`!try`\\-satsen, "
"kan undantaget hanteras av en :keyword:`except`\\-sats. Om undantaget inte "
"hanteras av en :keyword:`!except`\\-sats, kommer undantaget att tas upp igen "
"efter att :keyword:`!finally`\\-satsen har exekverats."

#: ../../tutorial/errors.rst:398
msgid ""
"An exception could occur during execution of an :keyword:`!except` or :"
"keyword:`!else` clause. Again, the exception is re-raised after the :keyword:"
"`!finally` clause has been executed."
msgstr ""
"Ett undantag kan inträffa under exekvering av en :keyword:`!except` eller :"
"keyword:`!else` klausul. Återigen, undantaget tas upp igen efter att :"
"keyword:`!finally`\\-satsen har exekverats."

#: ../../tutorial/errors.rst:402
msgid ""
"If the :keyword:`!finally` clause executes a :keyword:`break`, :keyword:"
"`continue` or :keyword:`return` statement, exceptions are not re-raised."
msgstr ""

#: ../../tutorial/errors.rst:406
msgid ""
"If the :keyword:`!try` statement reaches a :keyword:`break`, :keyword:"
"`continue` or :keyword:`return` statement, the :keyword:`!finally` clause "
"will execute just prior to the :keyword:`!break`, :keyword:`!continue` or :"
"keyword:`!return` statement's execution."
msgstr ""
"Om :keyword:`!try`\\-satsen når en :keyword:`break`\\-, :keyword:"
"`continue`\\- eller :keyword:`return`\\-sats, kommer :keyword:`!finally`\\-"
"satsen att exekveras strax före :keyword:`!break`\\-, :keyword:`!"
"continue`\\- eller :keyword:`!return`\\-satsens exekvering."

#: ../../tutorial/errors.rst:412
msgid ""
"If a :keyword:`!finally` clause includes a :keyword:`!return` statement, the "
"returned value will be the one from the :keyword:`!finally` clause's :"
"keyword:`!return` statement, not the value from the :keyword:`!try` "
"clause's :keyword:`!return` statement."
msgstr ""

#: ../../tutorial/errors.rst:418
msgid "For example::"
msgstr "Till exempel::"

#: ../../tutorial/errors.rst:429
msgid "A more complicated example::"
msgstr "Ett mer komplicerat exempel::"

#: ../../tutorial/errors.rst:454
msgid ""
"As you can see, the :keyword:`finally` clause is executed in any event.  "
"The :exc:`TypeError` raised by dividing two strings is not handled by the :"
"keyword:`except` clause and therefore re-raised after the :keyword:`!"
"finally` clause has been executed."
msgstr ""
"Som du kan se utförs :keyword:`finally`\\-satsen i vilket fall som helst.  "
"Det :exc:`TypeError` som uppstår när två strängar delas upp hanteras inte "
"av :keyword:`except`\\-satsen och uppstår därför igen efter att :keyword:`!"
"finally`\\-satsen har exekverats."

#: ../../tutorial/errors.rst:459
msgid ""
"In real world applications, the :keyword:`finally` clause is useful for "
"releasing external resources (such as files or network connections), "
"regardless of whether the use of the resource was successful."
msgstr ""
"I verkliga tillämpningar är klausulen :keyword:`finally` användbar för att "
"frigöra externa resurser (t.ex. filer eller nätverksanslutningar), oavsett "
"om användningen av resursen var framgångsrik eller inte."

#: ../../tutorial/errors.rst:467
msgid "Predefined Clean-up Actions"
msgstr "Fördefinierade saneringsåtgärder"

#: ../../tutorial/errors.rst:469
msgid ""
"Some objects define standard clean-up actions to be undertaken when the "
"object is no longer needed, regardless of whether or not the operation using "
"the object succeeded or failed. Look at the following example, which tries "
"to open a file and print its contents to the screen. ::"
msgstr ""
"Vissa objekt definierar standardstädningsåtgärder som ska vidtas när "
"objektet inte längre behövs, oavsett om operationen som använder objektet "
"lyckades eller misslyckades. Titta på följande exempel, som försöker öppna "
"en fil och skriva ut dess innehåll på skärmen. ::"

#: ../../tutorial/errors.rst:477
msgid ""
"The problem with this code is that it leaves the file open for an "
"indeterminate amount of time after this part of the code has finished "
"executing. This is not an issue in simple scripts, but can be a problem for "
"larger applications. The :keyword:`with` statement allows objects like files "
"to be used in a way that ensures they are always cleaned up promptly and "
"correctly. ::"
msgstr ""
"Problemet med den här koden är att den lämnar filen öppen under en obestämd "
"tid efter att den här delen av koden har exekverats. Detta är inte ett "
"problem i enkla skript, men kan vara ett problem för större applikationer. "
"Med :keyword:`with` kan objekt som filer användas på ett sätt som "
"säkerställer att de alltid rensas upp snabbt och korrekt. ::"

#: ../../tutorial/errors.rst:487
msgid ""
"After the statement is executed, the file *f* is always closed, even if a "
"problem was encountered while processing the lines. Objects which, like "
"files, provide predefined clean-up actions will indicate this in their "
"documentation."
msgstr ""
"Efter att satsen har utförts stängs alltid filen *f*, även om det uppstod "
"ett problem under bearbetningen av raderna. Objekt som, i likhet med filer, "
"har fördefinierade rensningsåtgärder kommer att ange detta i sin "
"dokumentation."

#: ../../tutorial/errors.rst:495
msgid "Raising and Handling Multiple Unrelated Exceptions"
msgstr "Upphävande och hantering av flera orelaterade undantag"

#: ../../tutorial/errors.rst:497
msgid ""
"There are situations where it is necessary to report several exceptions that "
"have occurred. This is often the case in concurrency frameworks, when "
"several tasks may have failed in parallel, but there are also other use "
"cases where it is desirable to continue execution and collect multiple "
"errors rather than raise the first exception."
msgstr ""
"Det finns situationer där det är nödvändigt att rapportera flera undantag "
"som har inträffat. Detta är ofta fallet i ramverk för samtidighet, när flera "
"uppgifter kan ha misslyckats parallellt, men det finns också andra "
"användningsfall där det är önskvärt att fortsätta exekveringen och samla in "
"flera fel i stället för att lösa ut det första undantaget."

#: ../../tutorial/errors.rst:503
msgid ""
"The builtin :exc:`ExceptionGroup` wraps a list of exception instances so "
"that they can be raised together. It is an exception itself, so it can be "
"caught like any other exception. ::"
msgstr ""
"Den inbyggda :exc:`ExceptionGroup` omsluter en lista med undantagsinstanser "
"så att de kan tas upp tillsammans. Det är ett undantag i sig, så det kan "
"fångas som vilket annat undantag som helst. ::"

#: ../../tutorial/errors.rst:529
msgid ""
"By using ``except*`` instead of ``except``, we can selectively handle only "
"the exceptions in the group that match a certain type. In the following "
"example, which shows a nested exception group, each ``except*`` clause "
"extracts from the group exceptions of a certain type while letting all other "
"exceptions propagate to other clauses and eventually to be reraised. ::"
msgstr ""
"Genom att använda ``except*`` istället för ``except`` kan vi selektivt "
"hantera endast de undantag i gruppen som matchar en viss typ. I följande "
"exempel, som visar en nästlad undantagsgrupp, extraherar varje ``except*``\\-"
"klausul undantag av en viss typ från gruppen medan alla andra undantag "
"sprids till andra klausuler och så småningom återkallas:"

#: ../../tutorial/errors.rst:572
msgid ""
"Note that the exceptions nested in an exception group must be instances, not "
"types. This is because in practice the exceptions would typically be ones "
"that have already been raised and caught by the program, along the following "
"pattern::"
msgstr ""
"Observera att undantagen i en undantagsgrupp måste vara instanser, inte "
"typer. Detta beror på att undantagen i praktiken vanligtvis är sådana som "
"redan har tagits upp och fångats upp av programmet, enligt följande mönster::"

#: ../../tutorial/errors.rst:592
msgid "Enriching Exceptions with Notes"
msgstr "Berika undantag med anteckningar"

#: ../../tutorial/errors.rst:594
msgid ""
"When an exception is created in order to be raised, it is usually "
"initialized with information that describes the error that has occurred. "
"There are cases where it is useful to add information after the exception "
"was caught. For this purpose, exceptions have a method ``add_note(note)`` "
"that accepts a string and adds it to the exception's notes list. The "
"standard traceback rendering includes all notes, in the order they were "
"added, after the exception. ::"
msgstr ""
"När ett undantag skapas för att fångas upp initialiseras det vanligtvis med "
"information som beskriver det fel som har inträffat. Det finns fall där det "
"är användbart att lägga till information efter att undantaget har fångats. "
"För detta ändamål har undantag en metod ``add_note(note)`` som accepterar en "
"sträng och lägger till den i undantagets anteckningslista. "
"Standardåtergivningen av spårningen innehåller alla anteckningar, i den "
"ordning de lades till, efter undantaget. ::"

#: ../../tutorial/errors.rst:615
msgid ""
"For example, when collecting exceptions into an exception group, we may want "
"to add context information for the individual errors. In the following each "
"exception in the group has a note indicating when this error has occurred. ::"
msgstr ""
"När vi t.ex. samlar undantag i en undantagsgrupp kan vi vilja lägga till "
"kontextinformation för de enskilda felen. I det följande har varje undantag "
"i gruppen en anteckning som anger när detta fel har inträffat. ::"
