# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001 Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# python-doc bot, 2025
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.14\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-07-11 14:21+0000\n"
"PO-Revision-Date: 2025-09-16 00:00+0000\n"
"Last-Translator: python-doc bot, 2025\n"
"Language-Team: Spanish (Spain) (https://app.transifex.com/python-doc/"
"teams/5390/es_ES/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es_ES\n"
"Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? "
"1 : 2;\n"

#: ../../c-api/exceptions.rst:8
msgid "Exception Handling"
msgstr "Gestión de excepciones"

#: ../../c-api/exceptions.rst:10
msgid ""
"The functions described in this chapter will let you handle and raise Python "
"exceptions.  It is important to understand some of the basics of Python "
"exception handling.  It works somewhat like the POSIX :c:data:`errno` "
"variable: there is a global indicator (per thread) of the last error that "
"occurred.  Most C API functions don't clear this on success, but will set it "
"to indicate the cause of the error on failure.  Most C API functions also "
"return an error indicator, usually ``NULL`` if they are supposed to return a "
"pointer, or ``-1`` if they return an integer (exception: the ``PyArg_*`` "
"functions return ``1`` for success and ``0`` for failure)."
msgstr ""

#: ../../c-api/exceptions.rst:20
msgid ""
"Concretely, the error indicator consists of three object pointers: the "
"exception's type, the exception's value, and the traceback object.  Any of "
"those pointers can be ``NULL`` if non-set (although some combinations are "
"forbidden, for example you can't have a non-``NULL`` traceback if the "
"exception type is ``NULL``)."
msgstr ""
"Concretamente, el indicador de error consta de tres punteros a objetos: el "
"tipo de la excepción, el valor de la excepción y el objeto traceback.  "
"Cualquiera de esos punteros puede ser ``NULL`` si no está establecido "
"(aunque algunas combinaciones están prohibidas, por ejemplo, no se puede "
"tener un traceback que no sea``NULL`` si el tipo de excepción es ``NULL``)."

#: ../../c-api/exceptions.rst:26
msgid ""
"When a function must fail because some function it called failed, it "
"generally doesn't set the error indicator; the function it called already "
"set it.  It is responsible for either handling the error and clearing the "
"exception or returning after cleaning up any resources it holds (such as "
"object references or memory allocations); it should *not* continue normally "
"if it is not prepared to handle the error.  If returning due to an error, it "
"is important to indicate to the caller that an error has been set.  If the "
"error is not handled or carefully propagated, additional calls into the "
"Python/C API may not behave as intended and may fail in mysterious ways."
msgstr ""
"Cuando una función debe fallar porque alguna función a la que llamó falló, "
"generalmente no establece el indicador de error; la función a la que llamó "
"ya lo estableció.  Es responsable de manejar el error y borrar la excepción "
"o volver después de limpiar cualquier recurso que tenga (como referencias a "
"objetos o asignaciones de memoria); \"no\" debería continuar normalmente si "
"no está preparada para manejar el error.  Si devuelve debido a un error, es "
"importante indicar a caller que se ha producido un error.  Si el error no es "
"manejado o propagado cuidadosamente, las llamadas adicionales a la API de "
"Python/C pueden no comportarse como se pretendía y pueden fallar de forma "
"misteriosa."

#: ../../c-api/exceptions.rst:37
msgid ""
"The error indicator is **not** the result of :func:`sys.exc_info`. The "
"former corresponds to an exception that is not yet caught (and is therefore "
"still propagating), while the latter returns an exception after it is caught "
"(and has therefore stopped propagating)."
msgstr ""

#: ../../c-api/exceptions.rst:44
msgid "Printing and clearing"
msgstr "Impresión y limpieza"

#: ../../c-api/exceptions.rst:49
msgid ""
"Clear the error indicator.  If the error indicator is not set, there is no "
"effect."
msgstr ""
"Borre el indicador de error.  Si el indicador de error no está activado, no "
"se produce ningún efecto."

#: ../../c-api/exceptions.rst:55
msgid ""
"Print a standard traceback to ``sys.stderr`` and clear the error indicator. "
"**Unless** the error is a ``SystemExit``, in that case no traceback is "
"printed and the Python process will exit with the error code specified by "
"the ``SystemExit`` instance."
msgstr ""
"Imprime un rastreo estándar en ``sys.stderr`` y borra el indicador de error. "
"**A menos que** el error sea un ``SystemExit``, en ese caso no se imprime "
"ningún rastreo y el proceso Python saldrá con el código de error "
"especificado por la instancia ``SystemExit``."

#: ../../c-api/exceptions.rst:60
msgid ""
"Call this function **only** when the error indicator is set.  Otherwise it "
"will cause a fatal error!"
msgstr ""
"Llame a esta función **only** cuando el indicador de error esté activado.  "
"De lo contrario, provocará un error fatal."

#: ../../c-api/exceptions.rst:63
msgid ""
"If *set_sys_last_vars* is nonzero, the variable :data:`sys.last_exc` is set "
"to the printed exception. For backwards compatibility, the deprecated "
"variables :data:`sys.last_type`, :data:`sys.last_value` and :data:`sys."
"last_traceback` are also set to the type, value and traceback of this "
"exception, respectively."
msgstr ""

#: ../../c-api/exceptions.rst:69
msgid "The setting of :data:`sys.last_exc` was added."
msgstr ""

#: ../../c-api/exceptions.rst:75
msgid "Alias for ``PyErr_PrintEx(1)``."
msgstr "Alias para ``PyErr_PrintEx(1)``."

#: ../../c-api/exceptions.rst:80
msgid ""
"Call :func:`sys.unraisablehook` using the current exception and *obj* "
"argument."
msgstr ""
"Llama a :func:`sys.unraisablehook` usando la excepción actual y el argumento "
"*obj*."

#: ../../c-api/exceptions.rst:83
msgid ""
"This utility function prints a warning message to ``sys.stderr`` when an "
"exception has been set but it is impossible for the interpreter to actually "
"raise the exception.  It is used, for example, when an exception occurs in "
"an :meth:`~object.__del__` method."
msgstr ""

#: ../../c-api/exceptions.rst:88
msgid ""
"The function is called with a single argument *obj* that identifies the "
"context in which the unraisable exception occurred. If possible, the repr of "
"*obj* will be printed in the warning message. If *obj* is ``NULL``, only the "
"traceback is printed."
msgstr ""

#: ../../c-api/exceptions.rst:93
msgid "An exception must be set when calling this function."
msgstr "Debe establecerse una excepción al llamar a esta función."

#: ../../c-api/exceptions.rst:95
msgid "Print a traceback. Print only traceback if *obj* is ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:98
msgid "Use :func:`sys.unraisablehook`."
msgstr ""

#: ../../c-api/exceptions.rst:104
msgid ""
"Similar to :c:func:`PyErr_WriteUnraisable`, but the *format* and subsequent "
"parameters help format the warning message; they have the same meaning and "
"values as in :c:func:`PyUnicode_FromFormat`. ``PyErr_WriteUnraisable(obj)`` "
"is roughly equivalent to ``PyErr_FormatUnraisable(\"Exception ignored in: "
"%R\", obj)``. If *format* is ``NULL``, only the traceback is printed."
msgstr ""

#: ../../c-api/exceptions.rst:116
msgid ""
"Print the standard traceback display of ``exc`` to ``sys.stderr``, including "
"chained exceptions and notes."
msgstr ""

#: ../../c-api/exceptions.rst:123
msgid "Raising exceptions"
msgstr "Planteamiento de excepciones"

#: ../../c-api/exceptions.rst:125
msgid ""
"These functions help you set the current thread's error indicator. For "
"convenience, some of these functions will always return a ``NULL`` pointer "
"for use in a ``return`` statement."
msgstr ""
"Estas funciones le ayudan a establecer el indicador de error del subproceso "
"actual. Por comodidad, algunas de estas funciones devolverán siempre un "
"puntero ``NULL`` para su uso en una sentencia ``return``."

#: ../../c-api/exceptions.rst:132
msgid ""
"This is the most common way to set the error indicator.  The first argument "
"specifies the exception type; it is normally one of the standard exceptions, "
"e.g. :c:data:`PyExc_RuntimeError`.  You need not create a new :term:`strong "
"reference` to it (e.g. with :c:func:`Py_INCREF`). The second argument is an "
"error message; it is decoded from ``'utf-8'``."
msgstr ""

#: ../../c-api/exceptions.rst:141
msgid ""
"This function is similar to :c:func:`PyErr_SetString` but lets you specify "
"an arbitrary Python object for the \"value\" of the exception."
msgstr ""
"Esta función es similar a :c:func:`PyErr_SetString` pero permite especificar "
"un objeto Python arbitrario para el \"valor\" de la excepción."

#: ../../c-api/exceptions.rst:147
msgid ""
"This function sets the error indicator and returns ``NULL``.  *exception* "
"should be a Python exception class.  The *format* and subsequent parameters "
"help format the error message; they have the same meaning and values as in :"
"c:func:`PyUnicode_FromFormat`. *format* is an ASCII-encoded string."
msgstr ""
"Esta función establece el indicador de error y devuelve ``NULL``.  "
"*exception* debe ser una clase de excepción de Python.  Los parámetros "
"*format* y siguientes ayudan a formatear el mensaje de error; tienen el "
"mismo significado y valores que en :c:func:`PyUnicode_FromFormat`. *format* "
"es una cadena codificada en ASCII."

#: ../../c-api/exceptions.rst:156
msgid ""
"Same as :c:func:`PyErr_Format`, but taking a :c:type:`va_list` argument "
"rather than a variable number of arguments."
msgstr ""
"Igual que :c:func:`PyErr_Format`, pero tomando un argumento :c:type:"
"`va_list` en lugar de un número variable de argumentos."

#: ../../c-api/exceptions.rst:164
msgid "This is a shorthand for ``PyErr_SetObject(type, Py_None)``."
msgstr "Se trata de una abreviatura de ``PyErr_SetObject(type, Py_None)``."

#: ../../c-api/exceptions.rst:169
msgid ""
"This is a shorthand for ``PyErr_SetString(PyExc_TypeError, message)``, where "
"*message* indicates that a built-in operation was invoked with an illegal "
"argument.  It is mostly for internal use."
msgstr ""
"Esta es una abreviatura de ``PyErr_SetString(PyExc_TypeError, message)``, "
"donde *message* indica que una operación incorporada fue invocada con un "
"argumento ilegal.  Es principalmente para uso interno."

#: ../../c-api/exceptions.rst:176
msgid ""
"This is a shorthand for ``PyErr_SetNone(PyExc_MemoryError)``; it returns "
"``NULL`` so an object allocation function can write ``return "
"PyErr_NoMemory();`` when it runs out of memory."
msgstr ""
"Es una abreviatura de ``PyErr_SetNone(PyExc_MemoryError)``; devuelve "
"``NULL`` para que una función de asignación de objetos pueda escribir "
"``return PyErr_NoMemory();`` cuando se quede sin memoria."

#: ../../c-api/exceptions.rst:185
msgid ""
"This is a convenience function to raise an exception when a C library "
"function has returned an error and set the C variable :c:data:`errno`.  It "
"constructs a tuple object whose first item is the integer :c:data:`errno` "
"value and whose second item is the corresponding error message (gotten from :"
"c:func:`!strerror`), and then calls ``PyErr_SetObject(type, object)``.  On "
"Unix, when the :c:data:`errno` value is :c:macro:`!EINTR`, indicating an "
"interrupted system call, this calls :c:func:`PyErr_CheckSignals`, and if "
"that set the error indicator, leaves it set to that.  The function always "
"returns ``NULL``, so a wrapper function around a system call can write "
"``return PyErr_SetFromErrno(type);`` when the system call returns an error."
msgstr ""

#: ../../c-api/exceptions.rst:199
msgid ""
"Similar to :c:func:`PyErr_SetFromErrno`, with the additional behavior that "
"if *filenameObject* is not ``NULL``, it is passed to the constructor of "
"*type* as a third parameter.  In the case of :exc:`OSError` exception, this "
"is used to define the :attr:`!filename` attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:208
msgid ""
"Similar to :c:func:`PyErr_SetFromErrnoWithFilenameObject`, but takes a "
"second filename object, for raising errors when a function that takes two "
"filenames fails."
msgstr ""
"Similar a :c:func:`PyErr_SetFromErrnoWithFilenameObject`, pero toma un "
"segundo objeto nombre de fichero, para lanzar errores cuando una función que "
"toma dos nombres de fichero falla."

#: ../../c-api/exceptions.rst:217
msgid ""
"Similar to :c:func:`PyErr_SetFromErrnoWithFilenameObject`, but the filename "
"is given as a C string.  *filename* is decoded from the :term:`filesystem "
"encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:224
msgid ""
"This is a convenience function to raise :exc:`OSError`. If called with "
"*ierr* of ``0``, the error code returned by a call to :c:func:`!"
"GetLastError` is used instead.  It calls the Win32 function :c:func:`!"
"FormatMessage` to retrieve the Windows description of error code given by "
"*ierr* or :c:func:`!GetLastError`, then it constructs a :exc:`OSError` "
"object with the :attr:`~OSError.winerror` attribute set to the error code, "
"the :attr:`~OSError.strerror` attribute set to the corresponding error "
"message (gotten from :c:func:`!FormatMessage`), and then calls "
"``PyErr_SetObject(PyExc_OSError, object)``. This function always returns "
"``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:234 ../../c-api/exceptions.rst:242
#: ../../c-api/exceptions.rst:253 ../../c-api/exceptions.rst:263
#: ../../c-api/exceptions.rst:271 ../../c-api/exceptions.rst:281
msgid "Availability"
msgstr ""

#: ../../c-api/exceptions.rst:239
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErr`, with an additional parameter "
"specifying the exception type to be raised."
msgstr ""
"Similar a :c:func:`PyErr_SetFromWindowsErr`, con un parámetro adicional que "
"especifica el tipo de excepción a lanzar."

#: ../../c-api/exceptions.rst:247
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErr`, with the additional behavior "
"that if *filename* is not ``NULL``, it is decoded from the filesystem "
"encoding (:func:`os.fsdecode`) and passed to the constructor of :exc:"
"`OSError` as a third parameter to be used to define the :attr:`!filename` "
"attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:258
msgid ""
"Similar to :c:func:`PyErr_SetExcFromWindowsErr`, with the additional "
"behavior that if *filename* is not ``NULL``, it is passed to the constructor "
"of :exc:`OSError` as a third parameter to be used to define the :attr:`!"
"filename` attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:268
msgid ""
"Similar to :c:func:`PyErr_SetExcFromWindowsErrWithFilenameObject`, but "
"accepts a second filename object."
msgstr ""
"Similar a :c:func:`PyErr_SetExcFromWindowsErrWithFilenameObject`, pero "
"acepta un segundo objeto filename."

#: ../../c-api/exceptions.rst:278
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErrWithFilename`, with an additional "
"parameter specifying the exception type to be raised."
msgstr ""
"Similar a :c:func:`PyErr_SetFromWindowsErrWithFilename`, con un parámetro "
"adicional que especifica el tipo de excepción a lanzar."

#: ../../c-api/exceptions.rst:286
msgid ""
"This is a convenience function to raise :exc:`ImportError`. *msg* will be "
"set as the exception's message string. *name* and *path*, both of which can "
"be ``NULL``, will be set as the :exc:`ImportError`'s respective ``name`` and "
"``path`` attributes."
msgstr ""
"Esta es una función práctica para lanzar :exc:`ImportError`. *msg* se "
"establecerá como la cadena de mensaje de la excepción. *name* y *path*, que "
"pueden ser ``NULL``, se establecerán como los atributos respectivos de :exc:"
"`ImportError` ``name`` y ``path``."

#: ../../c-api/exceptions.rst:296
msgid ""
"Much like :c:func:`PyErr_SetImportError` but this function allows for "
"specifying a subclass of :exc:`ImportError` to raise."
msgstr ""
"Muy similar a :c:func:`PyErr_SetImportError` pero esta función permite "
"especificar una subclase de :exc:`ImportError` para que se active."

#: ../../c-api/exceptions.rst:304
msgid ""
"Set file, line, and offset information for the current exception.  If the "
"current exception is not a :exc:`SyntaxError`, then it sets additional "
"attributes, which make the exception printing subsystem think the exception "
"is a :exc:`SyntaxError`."
msgstr ""
"Establece la información de archivo, línea y offset para la excepción "
"actual.  Si la excepción actual no es una :exc:`SyntaxError`, entonces "
"establece atributos adicionales, que hacen que el subsistema de impresión de "
"excepciones piense que la excepción es una :exc:`SyntaxError`."

#: ../../c-api/exceptions.rst:314
msgid ""
"Like :c:func:`PyErr_SyntaxLocationObject`, but *filename* is a byte string "
"decoded from the :term:`filesystem encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:322
msgid ""
"Like :c:func:`PyErr_SyntaxLocationEx`, but the *col_offset* parameter is "
"omitted."
msgstr ""
"Como :c:func:`PyErr_SyntaxLocationEx`, pero se omite el parámetro "
"*col_offset*."

#: ../../c-api/exceptions.rst:328
msgid ""
"This is a shorthand for ``PyErr_SetString(PyExc_SystemError, message)``, "
"where *message* indicates that an internal operation (e.g. a Python/C API "
"function) was invoked with an illegal argument.  It is mostly for internal "
"use."
msgstr ""
"Esta es una abreviatura de ``PyErr_SetString(PyExc_SystemError, message)``, "
"donde *message* indica que una operación interna (por ejemplo, una función "
"de la API de Python/C) se llamó con un argumento ilegal.  Es principalmente "
"para uso interno."

#: ../../c-api/exceptions.rst:335
msgid "Issuing warnings"
msgstr "Advertencias"

#: ../../c-api/exceptions.rst:337
msgid ""
"Use these functions to issue warnings from C code.  They mirror similar "
"functions exported by the Python :mod:`warnings` module.  They normally "
"print a warning message to *sys.stderr*; however, it is also possible that "
"the user has specified that warnings are to be turned into errors, and in "
"that case they will raise an exception.  It is also possible that the "
"functions raise an exception because of a problem with the warning "
"machinery. The return value is ``0`` if no exception is raised, or ``-1`` if "
"an exception is raised.  (It is not possible to determine whether a warning "
"message is actually printed, nor what the reason is for the exception; this "
"is intentional.)  If an exception is raised, the caller should do its normal "
"exception handling (for example, :c:func:`Py_DECREF` owned references and "
"return an error value)."
msgstr ""
"Utilizar estas funciones para emitir advertencias desde código C.  Reflejan "
"funciones similares exportadas por el módulo de Python :mod:`warnings`.  "
"Normalmente imprimen un mensaje de advertencia en *sys.stderr*; sin embargo, "
"también es posible que el usuario haya especificado que las advertencias se "
"conviertan en errores, y en ese caso lanzarán una excepción.  También es "
"posible que las funciones lancen una excepción debido a un problema con la "
"maquinaria de avisos. El valor de retorno es ``0`` si no se produce ninguna "
"excepción, o ``-1`` si se produce una excepción.  (No es posible determinar "
"si realmente se imprime un mensaje de advertencia, ni cuál es el motivo de "
"la excepción; esto es intencionado).  Si se produce una excepción, el "
"invocador debe hacer su manejo normal de excepciones (por ejemplo, :c:func:"
"`Py_DECREF` referencias propias y devolver un valor de error)."

#: ../../c-api/exceptions.rst:352
msgid ""
"Issue a warning message.  The *category* argument is a warning category (see "
"below) or ``NULL``; the *message* argument is a UTF-8 encoded string.  "
"*stack_level* is a positive number giving a number of stack frames; the "
"warning will be issued from the  currently executing line of code in that "
"stack frame.  A *stack_level* of 1 is the function calling :c:func:"
"`PyErr_WarnEx`, 2 is  the function above that, and so forth."
msgstr ""
"Emitir un mensaje de advertencia.  El argumento *category* es una categoría "
"de advertencia (ver más abajo) o ``NULL``; el argumento *message* es una "
"cadena codificada en UTF-8.  *stack_level* es un número positivo que da un "
"número de marcos de pila; la advertencia se emitirá desde la línea de código "
"actualmente en ejecución en ese marco de pila.  Un *stack_level* de 1 es la "
"función que llama a :c:func:`PyErr_WarnEx`, 2 es la función por encima de "
"ésta, y así sucesivamente."

#: ../../c-api/exceptions.rst:359
msgid ""
"Warning categories must be subclasses of :c:data:`PyExc_Warning`; :c:data:"
"`PyExc_Warning` is a subclass of :c:data:`PyExc_Exception`; the default "
"warning category is :c:data:`PyExc_RuntimeWarning`. The standard Python "
"warning categories are available as global variables whose names are "
"enumerated at :ref:`standardwarningcategories`."
msgstr ""
"Las categorías de advertencia deben ser subclases de :c:data:"
"`PyExc_Warning`; :c:data:`PyExc_Warning` es una subclase de :c:data:"
"`PyExc_Exception`; la categoría de advertencia por defecto es :c:data:"
"`PyExc_RuntimeWarning`. Las categorías de advertencia estándar de Python "
"están disponibles como variables globales cuyos nombres se enumeran en :ref:"
"`standardwarningcategories`."

#: ../../c-api/exceptions.rst:365
msgid ""
"For information about warning control, see the documentation for the :mod:"
"`warnings` module and the :option:`-W` option in the command line "
"documentation.  There is no C API for warning control."
msgstr ""
"Para obtener información sobre el control de avisos, ver la documentación "
"del módulo :mod:`warnings` y la opción :option:`-W` en la documentación de "
"la línea de comandos.  No existe una API en C para el control de avisos."

#: ../../c-api/exceptions.rst:372
msgid ""
"Issue a warning message with explicit control over all warning attributes.  "
"This is a straightforward wrapper around the Python function :func:`warnings."
"warn_explicit`; see there for more information.  The *module* and *registry* "
"arguments may be set to ``NULL`` to get the default effect described there."
msgstr ""
"Emitir un mensaje de advertencia con control explícito sobre todos los "
"atributos de advertencia.  Esta es una envoltura directa alrededor de la "
"función de Python :func:`warnings.warn_explicit`; ver eso para más "
"información.  Los argumentos *module* y *registry* pueden establecerse a "
"``NULL`` para obtener el efecto por defecto allí descrito."

#: ../../c-api/exceptions.rst:383
msgid ""
"Similar to :c:func:`PyErr_WarnExplicitObject` except that *message* and "
"*module* are UTF-8 encoded strings, and *filename* is decoded from the :term:"
"`filesystem encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:390
msgid ""
"Function similar to :c:func:`PyErr_WarnEx`, but use :c:func:"
"`PyUnicode_FromFormat` to format the warning message.  *format* is an ASCII-"
"encoded string."
msgstr ""
"Función similar a :c:func:`PyErr_WarnEx`, pero utiliza :c:func:"
"`PyUnicode_FromFormat` para dar formato al mensaje de advertencia.  *format* "
"es una cadena codificada en ASCII."

#: ../../c-api/exceptions.rst:399
msgid ""
"Function similar to :c:func:`PyErr_WarnFormat`, but *category* is :exc:"
"`ResourceWarning` and it passes *source* to :class:`!warnings."
"WarningMessage`."
msgstr ""

#: ../../c-api/exceptions.rst:406
msgid "Querying the error indicator"
msgstr "Consultar del indicador de error"

#: ../../c-api/exceptions.rst:410
msgid ""
"Test whether the error indicator is set.  If set, return the exception "
"*type* (the first argument to the last call to one of the ``PyErr_Set*`` "
"functions or to :c:func:`PyErr_Restore`).  If not set, return ``NULL``.  You "
"do not own a reference to the return value, so you do not need to :c:func:"
"`Py_DECREF` it."
msgstr ""

#: ../../c-api/exceptions.rst:416
msgid "The caller must have an :term:`attached thread state`."
msgstr ""

#: ../../c-api/exceptions.rst:420
msgid ""
"Do not compare the return value to a specific exception; use :c:func:"
"`PyErr_ExceptionMatches` instead, shown below.  (The comparison could easily "
"fail since the exception may be an instance instead of a class, in the case "
"of a class exception, or it may be a subclass of the expected exception.)"
msgstr ""
"No comparar el valor de retorno con una excepción específica; usar :c:func:"
"`PyErr_ExceptionMatches` en su lugar, como se muestra a continuación.  (La "
"comparación podría fallar fácilmente ya que la excepción puede ser una "
"instancia en lugar de una clase, en el caso de una excepción de clase, o "
"puede ser una subclase de la excepción esperada)."

#: ../../c-api/exceptions.rst:428
msgid ""
"Equivalent to ``PyErr_GivenExceptionMatches(PyErr_Occurred(), exc)``.  This "
"should only be called when an exception is actually set; a memory access "
"violation will occur if no exception has been raised."
msgstr ""
"Equivale a ``PyErr_GivenExceptionMatches(PyErr_Occurred(), exc)``. Sólo debe "
"invocarse cuando se produce una excepción; se producirá una violación de "
"acceso a memoria si no se ha lanzado ninguna excepción."

#: ../../c-api/exceptions.rst:435
msgid ""
"Return true if the *given* exception matches the exception type in *exc*.  "
"If *exc* is a class object, this also returns true when *given* is an "
"instance of a subclass.  If *exc* is a tuple, all exception types in the "
"tuple (and recursively in subtuples) are searched for a match."
msgstr ""
"Devuelve verdadero si la excepción *given* coincide con el tipo de excepción "
"en *exc*.  Si *exc* es un objeto de clase, también devuelve true cuando "
"*given* es una instancia de una subclase.  Si *exc* es una tupla, se buscan "
"todos los tipos de excepción en la tupla (y recursivamente en las subtuplas)."

#: ../../c-api/exceptions.rst:443
msgid ""
"Return the exception currently being raised, clearing the error indicator at "
"the same time. Return ``NULL`` if the error indicator is not set."
msgstr ""

#: ../../c-api/exceptions.rst:446
msgid ""
"This function is used by code that needs to catch exceptions, or code that "
"needs to save and restore the error indicator temporarily."
msgstr ""

#: ../../c-api/exceptions.rst:449 ../../c-api/exceptions.rst:493
msgid "For example::"
msgstr "Por ejemplo::"

#: ../../c-api/exceptions.rst:451
msgid ""
"{\n"
"   PyObject *exc = PyErr_GetRaisedException();\n"
"\n"
"   /* ... code that might produce other errors ... */\n"
"\n"
"   PyErr_SetRaisedException(exc);\n"
"}"
msgstr ""

#: ../../c-api/exceptions.rst:459
msgid ""
":c:func:`PyErr_GetHandledException`, to save the exception currently being "
"handled."
msgstr ""

#: ../../c-api/exceptions.rst:467
msgid ""
"Set *exc* as the exception currently being raised, clearing the existing "
"exception if one is set."
msgstr ""

#: ../../c-api/exceptions.rst:472
msgid "This call steals a reference to *exc*, which must be a valid exception."
msgstr ""

#: ../../c-api/exceptions.rst:481
msgid "Use :c:func:`PyErr_GetRaisedException` instead."
msgstr ""

#: ../../c-api/exceptions.rst:483
msgid ""
"Retrieve the error indicator into three variables whose addresses are "
"passed. If the error indicator is not set, set all three variables to "
"``NULL``.  If it is set, it will be cleared and you own a reference to each "
"object retrieved.  The value and traceback object may be ``NULL`` even when "
"the type object is not."
msgstr ""
"Recuperar el indicador de error en tres variables cuyas direcciones se "
"pasan. Si el indicador de error no está establecido, establece las tres "
"variables en ``NULL``. Si está establecido, se borrará y poseerá una "
"referencia a cada objeto recuperado.  El objeto value y traceback pueden ser "
"``NULL`` incluso cuando el objeto type no lo sea."

#: ../../c-api/exceptions.rst:490
msgid ""
"This function is normally only used by legacy code that needs to catch "
"exceptions or save and restore the error indicator temporarily."
msgstr ""

#: ../../c-api/exceptions.rst:495
msgid ""
"{\n"
"   PyObject *type, *value, *traceback;\n"
"   PyErr_Fetch(&type, &value, &traceback);\n"
"\n"
"   /* ... code that might produce other errors ... */\n"
"\n"
"   PyErr_Restore(type, value, traceback);\n"
"}"
msgstr ""

#: ../../c-api/exceptions.rst:509
msgid "Use :c:func:`PyErr_SetRaisedException` instead."
msgstr ""

#: ../../c-api/exceptions.rst:511
msgid ""
"Set the error indicator from the three objects, *type*, *value*, and "
"*traceback*, clearing the existing exception if one is set. If the objects "
"are ``NULL``, the error indicator is cleared.  Do not pass a ``NULL`` type "
"and non-``NULL`` value or traceback.  The exception type should be a class.  "
"Do not pass an invalid exception type or value. (Violating these rules will "
"cause subtle problems later.)  This call takes away a reference to each "
"object: you must own a reference to each object before the call and after "
"the call you no longer own these references.  (If you don't understand this, "
"don't use this function.  I warned you.)"
msgstr ""

#: ../../c-api/exceptions.rst:525
msgid ""
"This function is normally only used by legacy code that needs to save and "
"restore the error indicator temporarily. Use :c:func:`PyErr_Fetch` to save "
"the current error indicator."
msgstr ""

#: ../../c-api/exceptions.rst:534
msgid ""
"Use :c:func:`PyErr_GetRaisedException` instead, to avoid any possible de-"
"normalization."
msgstr ""

#: ../../c-api/exceptions.rst:537
msgid ""
"Under certain circumstances, the values returned by :c:func:`PyErr_Fetch` "
"below can be \"unnormalized\", meaning that ``*exc`` is a class object but "
"``*val`` is not an instance of the  same class.  This function can be used "
"to instantiate the class in that case.  If the values are already "
"normalized, nothing happens. The delayed normalization is implemented to "
"improve performance."
msgstr ""
"En determinadas circunstancias, los valores devueltos por :c:func:"
"`PyErr_Fetch` a continuación pueden ser \"unnormalized\", lo que significa "
"que ``*exc`` es un objeto de clase pero ``*val`` no es una instancia de la "
"misma clase.  Esta función puede utilizarse para instanciar la clase en ese "
"caso.  Si los valores ya están normalizados, no ocurre nada. La "
"normalización retardada se implementa para mejorar el rendimiento."

#: ../../c-api/exceptions.rst:545
msgid ""
"This function *does not* implicitly set the :attr:`~BaseException."
"__traceback__` attribute on the exception value. If setting the traceback "
"appropriately is desired, the following additional snippet is needed::"
msgstr ""

#: ../../c-api/exceptions.rst:550
msgid ""
"if (tb != NULL) {\n"
"  PyException_SetTraceback(val, tb);\n"
"}"
msgstr ""

#: ../../c-api/exceptions.rst:557
msgid ""
"Retrieve the active exception instance, as would be returned by :func:`sys."
"exception`. This refers to an exception that was *already caught*, not to an "
"exception that was freshly raised. Returns a new reference to the exception "
"or ``NULL``. Does not modify the interpreter's exception state."
msgstr ""

#: ../../c-api/exceptions.rst:564
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_SetHandledException` to restore or "
"clear the exception state."
msgstr ""

#: ../../c-api/exceptions.rst:573
msgid ""
"Set the active exception, as known from ``sys.exception()``.  This refers to "
"an exception that was *already caught*, not to an exception that was freshly "
"raised. To clear the exception state, pass ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:580
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_GetHandledException` to get the "
"exception state."
msgstr ""

#: ../../c-api/exceptions.rst:589
msgid ""
"Retrieve the old-style representation of the exception info, as known from :"
"func:`sys.exc_info`.  This refers to an exception that was *already caught*, "
"not to an exception that was freshly raised.  Returns new references for the "
"three objects, any of which may be ``NULL``.  Does not modify the exception "
"info state.  This function is kept for backwards compatibility. Prefer "
"using :c:func:`PyErr_GetHandledException`."
msgstr ""

#: ../../c-api/exceptions.rst:598
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_SetExcInfo` to restore or clear the "
"exception state."
msgstr ""
"Esta función no se utiliza normalmente por código que quiera manejar "
"excepciones. Más bien, se puede utilizar cuando el código necesita guardar y "
"restaurar el estado de excepción temporalmente.  Usar :c:func:"
"`PyErr_SetExcInfo` para restaurar o borrar el estado de excepción."

#: ../../c-api/exceptions.rst:608
msgid ""
"Set the exception info, as known from ``sys.exc_info()``.  This refers to an "
"exception that was *already caught*, not to an exception that was freshly "
"raised.  This function steals the references of the arguments. To clear the "
"exception state, pass ``NULL`` for all three arguments. This function is "
"kept for backwards compatibility. Prefer using :c:func:"
"`PyErr_SetHandledException`."
msgstr ""

#: ../../c-api/exceptions.rst:617
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_GetExcInfo` to read the exception "
"state."
msgstr ""
"Esta función no se utiliza normalmente por código que quiera manejar "
"excepciones. Más bien, se puede utilizar cuando el código necesita guardar y "
"restaurar el estado de excepción temporalmente.  Usar :c:func:"
"`PyErr_GetExcInfo` para leer el estado de excepción."

#: ../../c-api/exceptions.rst:624
msgid ""
"The ``type`` and ``traceback`` arguments are no longer used and can be NULL. "
"The interpreter now derives them from the exception instance (the ``value`` "
"argument). The function still steals references of all three arguments."
msgstr ""

#: ../../c-api/exceptions.rst:632
msgid "Signal Handling"
msgstr "Tratamiento de señales"

#: ../../c-api/exceptions.rst:642
msgid "This function interacts with Python's signal handling."
msgstr ""

#: ../../c-api/exceptions.rst:644
msgid ""
"If the function is called from the main thread and under the main Python "
"interpreter, it checks whether a signal has been sent to the processes and "
"if so, invokes the corresponding signal handler.  If the :mod:`signal` "
"module is supported, this can invoke a signal handler written in Python."
msgstr ""

#: ../../c-api/exceptions.rst:649
msgid ""
"The function attempts to handle all pending signals, and then returns ``0``. "
"However, if a Python signal handler raises an exception, the error indicator "
"is set and the function returns ``-1`` immediately (such that other pending "
"signals may not have been handled yet: they will be on the next :c:func:"
"`PyErr_CheckSignals()` invocation)."
msgstr ""

#: ../../c-api/exceptions.rst:655
msgid ""
"If the function is called from a non-main thread, or under a non-main Python "
"interpreter, it does nothing and returns ``0``."
msgstr ""

#: ../../c-api/exceptions.rst:658
msgid ""
"This function can be called by long-running C code that wants to be "
"interruptible by user requests (such as by pressing Ctrl-C)."
msgstr ""

#: ../../c-api/exceptions.rst:662
msgid ""
"The default Python signal handler for :c:macro:`!SIGINT` raises the :exc:"
"`KeyboardInterrupt` exception."
msgstr ""

#: ../../c-api/exceptions.rst:673
msgid ""
"Simulate the effect of a :c:macro:`!SIGINT` signal arriving. This is "
"equivalent to ``PyErr_SetInterruptEx(SIGINT)``."
msgstr ""

#: ../../c-api/exceptions.rst:677 ../../c-api/exceptions.rst:704
msgid ""
"This function is async-signal-safe.  It can be called without an :term:"
"`attached thread state` and from a C signal handler."
msgstr ""

#: ../../c-api/exceptions.rst:687
msgid ""
"Simulate the effect of a signal arriving. The next time :c:func:"
"`PyErr_CheckSignals` is called,  the Python signal handler for the given "
"signal number will be called."
msgstr ""

#: ../../c-api/exceptions.rst:691
msgid ""
"This function can be called by C code that sets up its own signal handling "
"and wants Python signal handlers to be invoked as expected when an "
"interruption is requested (for example when the user presses Ctrl-C to "
"interrupt an operation)."
msgstr ""

#: ../../c-api/exceptions.rst:696
msgid ""
"If the given signal isn't handled by Python (it was set to :py:const:`signal."
"SIG_DFL` or :py:const:`signal.SIG_IGN`), it will be ignored."
msgstr ""

#: ../../c-api/exceptions.rst:699
msgid ""
"If *signum* is outside of the allowed range of signal numbers, ``-1`` is "
"returned.  Otherwise, ``0`` is returned.  The error indicator is never "
"changed by this function."
msgstr ""

#: ../../c-api/exceptions.rst:712
msgid ""
"This utility function specifies a file descriptor to which the signal number "
"is written as a single byte whenever a signal is received. *fd* must be non-"
"blocking. It returns the previous such file descriptor."
msgstr ""
"Esta función de utilidad especifica un descriptor de archivo en el que el "
"número de señal se escribe como un único byte cada vez que se recibe una "
"señal. *fd* debe ser no bloqueante. Devuelve el descriptor de archivo "
"anterior."

#: ../../c-api/exceptions.rst:716
msgid ""
"The value ``-1`` disables the feature; this is the initial state. This is "
"equivalent to :func:`signal.set_wakeup_fd` in Python, but without any error "
"checking.  *fd* should be a valid file descriptor.  The function should only "
"be called from the main thread."
msgstr ""
"El valor ``-1`` desactiva la función; éste es el estado inicial. Es "
"equivalente a :func:`signal.set_wakeup_fd` en Python, pero sin comprobación "
"de errores.  *fd* debe ser un descriptor de fichero válido.  La función sólo "
"debe ser llamada desde el hilo principal."

#: ../../c-api/exceptions.rst:721
msgid "On Windows, the function now also supports socket handles."
msgstr "En Windows, la función también admite ahora los manejadores de socket."

#: ../../c-api/exceptions.rst:726
msgid "Exception Classes"
msgstr "Clases de excepción"

#: ../../c-api/exceptions.rst:730
msgid ""
"This utility function creates and returns a new exception class. The *name* "
"argument must be the name of the new exception, a C string of the form "
"``module.classname``.  The *base* and *dict* arguments are normally "
"``NULL``. This creates a class object derived from :exc:`Exception` "
"(accessible in C as :c:data:`PyExc_Exception`)."
msgstr ""
"Esta función de utilidad crea y devuelve una nueva clase de excepción. El "
"argumento *name* debe ser el nombre de la nueva excepción, una cadena C de "
"la forma ``module.classname``.  Los argumentos *base* y *dict* son "
"normalmente ``NULL``. Esto crea un objeto de clase derivado de :exc:"
"`Exception` (accesible en C como :c:data:`PyExc_Exception`)."

#: ../../c-api/exceptions.rst:736
msgid ""
"The :attr:`~type.__module__` attribute of the new class is set to the first "
"part (up to the last dot) of the *name* argument, and the class name is set "
"to the last part (after the last dot).  The *base* argument can be used to "
"specify alternate base classes; it can either be only one class or a tuple "
"of classes. The *dict* argument can be used to specify a dictionary of class "
"variables and methods."
msgstr ""

#: ../../c-api/exceptions.rst:745
msgid ""
"Same as :c:func:`PyErr_NewException`, except that the new exception class "
"can easily be given a docstring: If *doc* is non-``NULL``, it will be used "
"as the docstring for the exception class."
msgstr ""
"Igual que :c:func:`PyErr_NewException`, excepto que a la nueva clase de "
"excepción se le puede dar fácilmente un docstring: Si *doc* no es``NULL``, "
"se utilizará como docstring para la clase de excepción."

#: ../../c-api/exceptions.rst:754
msgid ""
"Return non-zero if *ob* is an exception class, zero otherwise. This function "
"always succeeds."
msgstr ""

#: ../../c-api/exceptions.rst:759
msgid "Return :c:member:`~PyTypeObject.tp_name` of the exception class *ob*."
msgstr ""

#: ../../c-api/exceptions.rst:763
msgid "Exception Objects"
msgstr "Objetos de excepción"

#: ../../c-api/exceptions.rst:767
msgid ""
"Return the traceback associated with the exception as a new reference, as "
"accessible from Python through the :attr:`~BaseException.__traceback__` "
"attribute. If there is no traceback associated, this returns ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:775
msgid ""
"Set the traceback associated with the exception to *tb*.  Use ``Py_None`` to "
"clear it."
msgstr ""
"Establece el rastreo asociado a la excepción en *tb*.  Utilice ``Py_None`` "
"para borrarlo."

#: ../../c-api/exceptions.rst:781
msgid ""
"Return the context (another exception instance during whose handling *ex* "
"was raised) associated with the exception as a new reference, as accessible "
"from Python through the :attr:`~BaseException.__context__` attribute. If "
"there is no context associated, this returns ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:789
msgid ""
"Set the context associated with the exception to *ctx*.  Use ``NULL`` to "
"clear it.  There is no type check to make sure that *ctx* is an exception "
"instance. This steals a reference to *ctx*."
msgstr ""
"Establece el contexto asociado a la excepción en *ctx*.  Utilice ``NULL`` "
"para borrarlo.  No hay comprobación de tipo para asegurarse de que *ctx* es "
"una instancia de excepción. Esto roba una referencia a *ctx*."

#: ../../c-api/exceptions.rst:796
msgid ""
"Return the cause (either an exception instance, or ``None``, set by "
"``raise ... from ...``) associated with the exception as a new reference, as "
"accessible from Python through the :attr:`~BaseException.__cause__` "
"attribute."
msgstr ""

#: ../../c-api/exceptions.rst:804
msgid ""
"Set the cause associated with the exception to *cause*.  Use ``NULL`` to "
"clear it.  There is no type check to make sure that *cause* is either an "
"exception instance or ``None``.  This steals a reference to *cause*."
msgstr ""

#: ../../c-api/exceptions.rst:808
msgid ""
"The :attr:`~BaseException.__suppress_context__` attribute is implicitly set "
"to ``True`` by this function."
msgstr ""

#: ../../c-api/exceptions.rst:814
msgid "Return :attr:`~BaseException.args` of exception *ex*."
msgstr ""

#: ../../c-api/exceptions.rst:819
msgid "Set :attr:`~BaseException.args` of exception *ex* to *args*."
msgstr ""

#: ../../c-api/exceptions.rst:823
msgid ""
"Implement part of the interpreter's implementation of :keyword:`!except*`. "
"*orig* is the original exception that was caught, and *excs* is the list of "
"the exceptions that need to be raised. This list contains the unhandled part "
"of *orig*, if any, as well as the exceptions that were raised from the :"
"keyword:`!except*` clauses (so they have a different traceback from *orig*) "
"and those that were reraised (and have the same traceback as *orig*). Return "
"the :exc:`ExceptionGroup` that needs to be reraised in the end, or ``None`` "
"if there is nothing to reraise."
msgstr ""

#: ../../c-api/exceptions.rst:837
msgid "Unicode Exception Objects"
msgstr "Objetos de excepción Unicode"

#: ../../c-api/exceptions.rst:839
msgid ""
"The following functions are used to create and modify Unicode exceptions "
"from C."
msgstr ""
"Las siguientes funciones se utilizan para crear y modificar excepciones "
"Unicode desde C."

#: ../../c-api/exceptions.rst:843
msgid ""
"Create a :class:`UnicodeDecodeError` object with the attributes *encoding*, "
"*object*, *length*, *start*, *end* and *reason*. *encoding* and *reason* are "
"UTF-8 encoded strings."
msgstr ""
"Crea un objeto :class:`UnicodeDecodeError` con los atributos *encoding*, "
"*object*, *length*, *start*, *end* y *reason*. *encoding* y *reason* son "
"cadenas codificadas en UTF-8."

#: ../../c-api/exceptions.rst:850
msgid "Return the *encoding* attribute of the given exception object."
msgstr "Devuelve el atributo *encoding* del objeto de excepción dado."

#: ../../c-api/exceptions.rst:856
msgid "Return the *object* attribute of the given exception object."
msgstr "Devuelve el atributo *object* del objeto de excepción dado."

#: ../../c-api/exceptions.rst:862
msgid ""
"Get the *start* attribute of the given exception object and place it into "
"*\\*start*.  *start* must not be ``NULL``.  Return ``0`` on success, ``-1`` "
"on failure."
msgstr ""
"Obtiene el atributo *start* del objeto de excepción dado y lo coloca en "
"*\\*start*.  *start* no debe ser ``NULL``.  Devuelve ``0`` en caso de éxito, "
"``-1`` en caso de fallo."

#: ../../c-api/exceptions.rst:866
msgid ""
"If the :attr:`UnicodeError.object` is an empty sequence, the resulting "
"*start* is ``0``. Otherwise, it is clipped to ``[0, len(object) - 1]``."
msgstr ""

#: ../../c-api/exceptions.rst:869
msgid ":attr:`UnicodeError.start`"
msgstr ""

#: ../../c-api/exceptions.rst:875
msgid ""
"Set the *start* attribute of the given exception object to *start*. Return "
"``0`` on success, ``-1`` on failure."
msgstr ""

#: ../../c-api/exceptions.rst:880
msgid ""
"While passing a negative *start* does not raise an exception, the "
"corresponding getters will not consider it as a relative offset."
msgstr ""

#: ../../c-api/exceptions.rst:888
msgid ""
"Get the *end* attribute of the given exception object and place it into "
"*\\*end*.  *end* must not be ``NULL``.  Return ``0`` on success, ``-1`` on "
"failure."
msgstr ""
"Obtiene el atributo *end* del objeto de excepción dado y lo coloca en "
"*\\*end*.  *end* no debe ser ``NULL``.  Devuelve ``0`` en caso de éxito, "
"``-1`` en caso de fallo."

#: ../../c-api/exceptions.rst:892
msgid ""
"If the :attr:`UnicodeError.object` is an empty sequence, the resulting *end* "
"is ``0``. Otherwise, it is clipped to ``[1, len(object)]``."
msgstr ""

#: ../../c-api/exceptions.rst:899
msgid ""
"Set the *end* attribute of the given exception object to *end*.  Return "
"``0`` on success, ``-1`` on failure."
msgstr ""
"Establece el atributo *end* del objeto de excepción dado a *end*.  Devuelve "
"``0`` en caso de éxito, ``-1`` en caso de fallo."

#: ../../c-api/exceptions.rst:902
msgid ":attr:`UnicodeError.end`"
msgstr ""

#: ../../c-api/exceptions.rst:908
msgid "Return the *reason* attribute of the given exception object."
msgstr "Devuelve el atributo *reason* del objeto de excepción dado."

#: ../../c-api/exceptions.rst:914
msgid ""
"Set the *reason* attribute of the given exception object to *reason*.  "
"Return ``0`` on success, ``-1`` on failure."
msgstr ""
"Establece el atributo *reason* del objeto de excepción dado a *reason*.  "
"Devuelve ``0`` en caso de éxito, ``-1`` en caso de fallo."

#: ../../c-api/exceptions.rst:921
msgid "Recursion Control"
msgstr "Control de recursividad"

#: ../../c-api/exceptions.rst:923
msgid ""
"These two functions provide a way to perform safe recursive calls at the C "
"level, both in the core and in extension modules.  They are needed if the "
"recursive code does not necessarily invoke Python code (which tracks its "
"recursion depth automatically). They are also not needed for *tp_call* "
"implementations because the :ref:`call protocol <call>` takes care of "
"recursion handling."
msgstr ""
"Estas dos funciones proporcionan una forma de realizar llamadas recursivas "
"seguras a nivel de C, tanto en el núcleo como en los módulos de extensión.  "
"Son necesarias si el código recursivo no invoca necesariamente código Python "
"(que rastrea su profundidad de recursión automáticamente). Tampoco son "
"necesarias para implementaciones *tp_call* porque el protocolo :ref:`call "
"<call>` se encarga de la gestión de la recursividad."

#: ../../c-api/exceptions.rst:932
msgid "Marks a point where a recursive C-level call is about to be performed."
msgstr ""
"Marca un punto en el que se va a realizar una llamada recursiva de nivel C."

#: ../../c-api/exceptions.rst:934
msgid ""
"The function then checks if the stack limit is reached.  If this is the "
"case, a :exc:`RecursionError` is set and a nonzero value is returned. "
"Otherwise, zero is returned."
msgstr ""

#: ../../c-api/exceptions.rst:938
msgid ""
"*where* should be a UTF-8 encoded string such as ``\" in instance check\"`` "
"to be concatenated to the :exc:`RecursionError` message caused by the "
"recursion depth limit."
msgstr ""
"*where* debe ser una cadena codificada en UTF-8 como ``\" in instance "
"check\"`` para concatenadarse al mensaje :exc:`RecursionError` causado por "
"el límite de profundidad de recursión."

#: ../../c-api/exceptions.rst:942 ../../c-api/exceptions.rst:950
msgid ""
"This function is now also available in the :ref:`limited API <limited-c-"
"api>`."
msgstr ""

#: ../../c-api/exceptions.rst:947
msgid ""
"Ends a :c:func:`Py_EnterRecursiveCall`.  Must be called once for each "
"*successful* invocation of :c:func:`Py_EnterRecursiveCall`."
msgstr ""
"Finaliza :c:func:`Py_EnterRecursiveCall`. Debe invocarse una vez por cada "
"invocación *con éxito* de :c:func:`Py_EnterRecursiveCall`."

#: ../../c-api/exceptions.rst:953
msgid ""
"Properly implementing :c:member:`~PyTypeObject.tp_repr` for container types "
"requires special recursion handling.  In addition to protecting the stack, :"
"c:member:`~PyTypeObject.tp_repr` also needs to track objects to prevent "
"cycles.  The following two functions facilitate this functionality.  "
"Effectively, these are the C equivalent to :func:`reprlib.recursive_repr`."
msgstr ""
"La correcta implementación de :c:member:`~PyTypeObject.tp_repr` para tipos "
"contenedores requiere un manejo especial de la recursividad.  Además de "
"proteger la pila, :c:member:`~PyTypeObject.tp_repr` también necesita "
"rastrear objetos para evitar ciclos.  Las dos funciones siguientes facilitan "
"esta funcionalidad.  De hecho, son el equivalente en C a :func:`reprlib."
"recursive_repr`."

#: ../../c-api/exceptions.rst:961
msgid ""
"Called at the beginning of the :c:member:`~PyTypeObject.tp_repr` "
"implementation to detect cycles."
msgstr ""
"Llamada al principio de la implementación de :c:member:`~PyTypeObject."
"tp_repr` para detectar ciclos."

#: ../../c-api/exceptions.rst:964
msgid ""
"If the object has already been processed, the function returns a positive "
"integer.  In that case the :c:member:`~PyTypeObject.tp_repr` implementation "
"should return a string object indicating a cycle.  As examples, :class:"
"`dict` objects return ``{...}`` and :class:`list` objects return ``[...]``."
msgstr ""
"Si el objeto ya ha sido procesado, la función devuelve un número entero "
"positivo.  En ese caso, la implementación de :c:member:`~PyTypeObject."
"tp_repr` debe devolver un objeto de cadena que indique un ciclo.  Como "
"ejemplos, los objetos :class:`dict` devuelven ``{...}`` y los objetos :class:"
"`list` devuelven ``[...]``."

#: ../../c-api/exceptions.rst:970
msgid ""
"The function will return a negative integer if the recursion limit is "
"reached.  In that case the :c:member:`~PyTypeObject.tp_repr` implementation "
"should typically return ``NULL``."
msgstr ""
"La función devolverá un entero negativo si se alcanza el límite de "
"recursión.  En ese caso, la implementación de :c:member:`~PyTypeObject."
"tp_repr` debería devolver ``NULL``."

#: ../../c-api/exceptions.rst:974
msgid ""
"Otherwise, the function returns zero and the :c:member:`~PyTypeObject."
"tp_repr` implementation can continue normally."
msgstr ""
"En caso contrario, la función devuelve cero y la aplicación :c:member:"
"`~PyTypeObject.tp_repr` puede continuar normalmente."

#: ../../c-api/exceptions.rst:979
msgid ""
"Ends a :c:func:`Py_ReprEnter`.  Must be called once for each invocation of :"
"c:func:`Py_ReprEnter` that returns zero."
msgstr ""
"Finaliza un :c:func:`Py_ReprEnter`. Debe llamarse una vez por cada "
"invocación de :c:func:`Py_ReprEnter` que devuelva cero."

#: ../../c-api/exceptions.rst:986
msgid "Exception and warning types"
msgstr ""

#: ../../c-api/exceptions.rst:988
msgid ""
"All standard Python exceptions and warning categories are available as "
"global variables whose names are ``PyExc_`` followed by the Python exception "
"name. These have the type :c:expr:`PyObject*`; they are all class objects."
msgstr ""

#: ../../c-api/exceptions.rst:992
msgid "For completeness, here are all the variables:"
msgstr ""

#: ../../c-api/exceptions.rst:995
msgid "Exception types"
msgstr ""

#: ../../c-api/exceptions.rst:1002 ../../c-api/exceptions.rst:1148
#: ../../c-api/exceptions.rst:1178
msgid "C name"
msgstr ""

#: ../../c-api/exceptions.rst:1003 ../../c-api/exceptions.rst:1149
#: ../../c-api/exceptions.rst:1179
msgid "Python name"
msgstr ""

#: ../../c-api/exceptions.rst:1005
msgid ":exc:`BaseException`"
msgstr ":exc:`BaseException`"

#: ../../c-api/exceptions.rst:1007
msgid ":exc:`BaseExceptionGroup`"
msgstr ""

#: ../../c-api/exceptions.rst:1009
msgid ":exc:`Exception`"
msgstr ":exc:`Exception`"

#: ../../c-api/exceptions.rst:1011
msgid ":exc:`ArithmeticError`"
msgstr ":exc:`ArithmeticError`"

#: ../../c-api/exceptions.rst:1013
msgid ":exc:`AssertionError`"
msgstr ":exc:`AssertionError`"

#: ../../c-api/exceptions.rst:1015
msgid ":exc:`AttributeError`"
msgstr ":exc:`AttributeError`"

#: ../../c-api/exceptions.rst:1017
msgid ":exc:`BlockingIOError`"
msgstr ":exc:`BlockingIOError`"

#: ../../c-api/exceptions.rst:1019
msgid ":exc:`BrokenPipeError`"
msgstr ":exc:`BrokenPipeError`"

#: ../../c-api/exceptions.rst:1021
msgid ":exc:`BufferError`"
msgstr ":exc:`BufferError`"

#: ../../c-api/exceptions.rst:1023
msgid ":exc:`ChildProcessError`"
msgstr ":exc:`ChildProcessError`"

#: ../../c-api/exceptions.rst:1025
msgid ":exc:`ConnectionAbortedError`"
msgstr ":exc:`ConnectionAbortedError`"

#: ../../c-api/exceptions.rst:1027
msgid ":exc:`ConnectionError`"
msgstr ":exc:`ConnectionError`"

#: ../../c-api/exceptions.rst:1029
msgid ":exc:`ConnectionRefusedError`"
msgstr ":exc:`ConnectionRefusedError`"

#: ../../c-api/exceptions.rst:1031
msgid ":exc:`ConnectionResetError`"
msgstr ":exc:`ConnectionResetError`"

#: ../../c-api/exceptions.rst:1033
msgid ":exc:`EOFError`"
msgstr ":exc:`EOFError`"

#: ../../c-api/exceptions.rst:1035
msgid ":exc:`FileExistsError`"
msgstr ":exc:`FileExistsError`"

#: ../../c-api/exceptions.rst:1037
msgid ":exc:`FileNotFoundError`"
msgstr ":exc:`FileNotFoundError`"

#: ../../c-api/exceptions.rst:1039
msgid ":exc:`FloatingPointError`"
msgstr ":exc:`FloatingPointError`"

#: ../../c-api/exceptions.rst:1041
msgid ":exc:`GeneratorExit`"
msgstr ":exc:`GeneratorExit`"

#: ../../c-api/exceptions.rst:1043
msgid ":exc:`ImportError`"
msgstr ":exc:`ImportError`"

#: ../../c-api/exceptions.rst:1045
msgid ":exc:`IndentationError`"
msgstr ":exc:`IndentationError`"

#: ../../c-api/exceptions.rst:1047
msgid ":exc:`IndexError`"
msgstr ":exc:`IndexError`"

#: ../../c-api/exceptions.rst:1049
msgid ":exc:`InterruptedError`"
msgstr ":exc:`InterruptedError`"

#: ../../c-api/exceptions.rst:1051
msgid ":exc:`IsADirectoryError`"
msgstr ":exc:`IsADirectoryError`"

#: ../../c-api/exceptions.rst:1053
msgid ":exc:`KeyError`"
msgstr ":exc:`KeyError`"

#: ../../c-api/exceptions.rst:1055
msgid ":exc:`KeyboardInterrupt`"
msgstr ":exc:`KeyboardInterrupt`"

#: ../../c-api/exceptions.rst:1057
msgid ":exc:`LookupError`"
msgstr ":exc:`LookupError`"

#: ../../c-api/exceptions.rst:1059
msgid ":exc:`MemoryError`"
msgstr ":exc:`MemoryError`"

#: ../../c-api/exceptions.rst:1061
msgid ":exc:`ModuleNotFoundError`"
msgstr ":exc:`ModuleNotFoundError`"

#: ../../c-api/exceptions.rst:1063
msgid ":exc:`NameError`"
msgstr ":exc:`NameError`"

#: ../../c-api/exceptions.rst:1065
msgid ":exc:`NotADirectoryError`"
msgstr ":exc:`NotADirectoryError`"

#: ../../c-api/exceptions.rst:1067
msgid ":exc:`NotImplementedError`"
msgstr ":exc:`NotImplementedError`"

#: ../../c-api/exceptions.rst:1069 ../../c-api/exceptions.rst:1152
#: ../../c-api/exceptions.rst:1155 ../../c-api/exceptions.rst:1158
msgid ":exc:`OSError`"
msgstr ":exc:`OSError`"

#: ../../c-api/exceptions.rst:1071
msgid ":exc:`OverflowError`"
msgstr ":exc:`OverflowError`"

#: ../../c-api/exceptions.rst:1073
msgid ":exc:`PermissionError`"
msgstr ":exc:`PermissionError`"

#: ../../c-api/exceptions.rst:1075
msgid ":exc:`ProcessLookupError`"
msgstr ":exc:`ProcessLookupError`"

#: ../../c-api/exceptions.rst:1077
msgid ":exc:`PythonFinalizationError`"
msgstr ""

#: ../../c-api/exceptions.rst:1079
msgid ":exc:`RecursionError`"
msgstr ":exc:`RecursionError`"

#: ../../c-api/exceptions.rst:1081
msgid ":exc:`ReferenceError`"
msgstr ":exc:`ReferenceError`"

#: ../../c-api/exceptions.rst:1083
msgid ":exc:`RuntimeError`"
msgstr ":exc:`RuntimeError`"

#: ../../c-api/exceptions.rst:1085
msgid ":exc:`StopAsyncIteration`"
msgstr ":exc:`StopAsyncIteration`"

#: ../../c-api/exceptions.rst:1087
msgid ":exc:`StopIteration`"
msgstr ":exc:`StopIteration`"

#: ../../c-api/exceptions.rst:1089
msgid ":exc:`SyntaxError`"
msgstr ":exc:`SyntaxError`"

#: ../../c-api/exceptions.rst:1091
msgid ":exc:`SystemError`"
msgstr ":exc:`SystemError`"

#: ../../c-api/exceptions.rst:1093
msgid ":exc:`SystemExit`"
msgstr ":exc:`SystemExit`"

#: ../../c-api/exceptions.rst:1095
msgid ":exc:`TabError`"
msgstr ":exc:`TabError`"

#: ../../c-api/exceptions.rst:1097
msgid ":exc:`TimeoutError`"
msgstr ":exc:`TimeoutError`"

#: ../../c-api/exceptions.rst:1099
msgid ":exc:`TypeError`"
msgstr ":exc:`TypeError`"

#: ../../c-api/exceptions.rst:1101
msgid ":exc:`UnboundLocalError`"
msgstr ":exc:`UnboundLocalError`"

#: ../../c-api/exceptions.rst:1103
msgid ":exc:`UnicodeDecodeError`"
msgstr ":exc:`UnicodeDecodeError`"

#: ../../c-api/exceptions.rst:1105
msgid ":exc:`UnicodeEncodeError`"
msgstr ":exc:`UnicodeEncodeError`"

#: ../../c-api/exceptions.rst:1107
msgid ":exc:`UnicodeError`"
msgstr ":exc:`UnicodeError`"

#: ../../c-api/exceptions.rst:1109
msgid ":exc:`UnicodeTranslateError`"
msgstr ":exc:`UnicodeTranslateError`"

#: ../../c-api/exceptions.rst:1111
msgid ":exc:`ValueError`"
msgstr ":exc:`ValueError`"

#: ../../c-api/exceptions.rst:1113
msgid ":exc:`ZeroDivisionError`"
msgstr ":exc:`ZeroDivisionError`"

#: ../../c-api/exceptions.rst:1115
msgid ""
":c:data:`PyExc_BlockingIOError`, :c:data:`PyExc_BrokenPipeError`, :c:data:"
"`PyExc_ChildProcessError`, :c:data:`PyExc_ConnectionError`, :c:data:"
"`PyExc_ConnectionAbortedError`, :c:data:`PyExc_ConnectionRefusedError`, :c:"
"data:`PyExc_ConnectionResetError`, :c:data:`PyExc_FileExistsError`, :c:data:"
"`PyExc_FileNotFoundError`, :c:data:`PyExc_InterruptedError`, :c:data:"
"`PyExc_IsADirectoryError`, :c:data:`PyExc_NotADirectoryError`, :c:data:"
"`PyExc_PermissionError`, :c:data:`PyExc_ProcessLookupError` and :c:data:"
"`PyExc_TimeoutError` were introduced following :pep:`3151`."
msgstr ""
":c:data:`PyExc_BlockingIOError`, :c:data:`PyExc_BrokenPipeError`, :c:data:"
"`PyExc_ChildProcessError`, :c:data:`PyExc_ConnectionError`, :c:data:"
"`PyExc_ConnectionAbortedError`, :c:data:`PyExc_ConnectionRefusedError`, :c:"
"data:`PyExc_ConnectionResetError`, :c:data:`PyExc_FileExistsError`, :c:data:"
"`PyExc_FileNotFoundError`, :c:data:`PyExc_InterruptedError`, :c:data:"
"`PyExc_IsADirectoryError`, :c:data:`PyExc_NotADirectoryError`, :c:data:"
"`PyExc_PermissionError`, :c:data:`PyExc_ProcessLookupError` y :c:data:"
"`PyExc_TimeoutError` se introdujeron a continuación de :pep:`3151`."

#: ../../c-api/exceptions.rst:1125
msgid ":c:data:`PyExc_StopAsyncIteration` and :c:data:`PyExc_RecursionError`."
msgstr ":c:data:`PyExc_StopAsyncIteration` y :c:data:`PyExc_RecursionError`."

#: ../../c-api/exceptions.rst:1128
msgid ":c:data:`PyExc_ModuleNotFoundError`."
msgstr ":c:data:`PyExc_ModuleNotFoundError`."

#: ../../c-api/exceptions.rst:1131
msgid ":c:data:`PyExc_BaseExceptionGroup`."
msgstr ""

#: ../../c-api/exceptions.rst:1136
msgid "OSError aliases"
msgstr ""

#: ../../c-api/exceptions.rst:1138
msgid "The following are a compatibility aliases to :c:data:`PyExc_OSError`."
msgstr ""

#: ../../c-api/exceptions.rst:1140
msgid "These aliases used to be separate exception types."
msgstr "Estos alias solían ser tipos de excepción independientes."

#: ../../c-api/exceptions.rst:1150
msgid "Notes"
msgstr "Notas"

#: ../../c-api/exceptions.rst:1159
msgid "[win]_"
msgstr ""

#: ../../c-api/exceptions.rst:1161
msgid "Notes:"
msgstr "Notas:"

#: ../../c-api/exceptions.rst:1164
msgid ""
":c:var:`!PyExc_WindowsError` is only defined on Windows; protect code that "
"uses this by testing that the preprocessor macro ``MS_WINDOWS`` is defined."
msgstr ""

#: ../../c-api/exceptions.rst:1171
msgid "Warning types"
msgstr ""

#: ../../c-api/exceptions.rst:1181
msgid ":exc:`Warning`"
msgstr ":exc:`Warning`"

#: ../../c-api/exceptions.rst:1183
msgid ":exc:`BytesWarning`"
msgstr ":exc:`BytesWarning`"

#: ../../c-api/exceptions.rst:1185
msgid ":exc:`DeprecationWarning`"
msgstr ":exc:`DeprecationWarning`"

#: ../../c-api/exceptions.rst:1187
msgid ":exc:`EncodingWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1189
msgid ":exc:`FutureWarning`"
msgstr ":exc:`FutureWarning`"

#: ../../c-api/exceptions.rst:1191
msgid ":exc:`ImportWarning`"
msgstr ":exc:`ImportWarning`"

#: ../../c-api/exceptions.rst:1193
msgid ":exc:`PendingDeprecationWarning`"
msgstr ":exc:`PendingDeprecationWarning`"

#: ../../c-api/exceptions.rst:1195
msgid ":exc:`ResourceWarning`"
msgstr ":exc:`ResourceWarning`"

#: ../../c-api/exceptions.rst:1197
msgid ":exc:`RuntimeWarning`"
msgstr ":exc:`RuntimeWarning`"

#: ../../c-api/exceptions.rst:1199
msgid ":exc:`SyntaxWarning`"
msgstr ":exc:`SyntaxWarning`"

#: ../../c-api/exceptions.rst:1201
msgid ":exc:`UnicodeWarning`"
msgstr ":exc:`UnicodeWarning`"

#: ../../c-api/exceptions.rst:1203
msgid ":exc:`UserWarning`"
msgstr ":exc:`UserWarning`"

#: ../../c-api/exceptions.rst:1205
msgid ":c:data:`PyExc_ResourceWarning`."
msgstr ":c:data:`PyExc_ResourceWarning`."

#: ../../c-api/exceptions.rst:1208
msgid ":c:data:`PyExc_EncodingWarning`."
msgstr ""

#: ../../c-api/exceptions.rst:183
msgid "strerror (C function)"
msgstr ""

#: ../../c-api/exceptions.rst:637 ../../c-api/exceptions.rst:668
#: ../../c-api/exceptions.rst:683
msgid "module"
msgstr "módulo"

#: ../../c-api/exceptions.rst:637 ../../c-api/exceptions.rst:668
#: ../../c-api/exceptions.rst:683
msgid "signal"
msgstr "señal"

#: ../../c-api/exceptions.rst:637 ../../c-api/exceptions.rst:668
msgid "SIGINT (C macro)"
msgstr ""

#: ../../c-api/exceptions.rst:637 ../../c-api/exceptions.rst:668
#: ../../c-api/exceptions.rst:683
msgid "KeyboardInterrupt (built-in exception)"
msgstr ""
